== Chapter II.

[.chapter-synopsis]
* Prospect of a Religious Visit to Friends in North America
* Voyage There and Landing at Boston In 1794

In the year 1793, a very weighty concern revived in my mind, to visit Friends in America;
of which I had had some prospect, before leaving England;
but for several years it had disappeared, so that I hoped I should have been excused:
but it now returned with so much weight, that I was constrained to give up to it,
though not without considerable conflict.
I felt so poor a creature every way,
and ill qualified for what appeared to me so great an undertaking,
that I was often sunk very low; and the prospect of leaving my family,
now consisting of nine children, who seemed greatly to need my care and assistance,
appeared sometimes very trying.
But I had covenanted to do whatever the Lord required,
if He would condescend to give me satisfactory evidence of his will,
which He so far did from time to time, that I had no excuse left:
I therefore gave up to it,
and laid my concern before my Monthly Meeting and Half-year`'s Meeting;
and having received certificates of their sympathy and concurrence,
I proceeded to London,
where I had also the unity of the Yearly Meeting of Ministers and Elders;
and thus the way seemed clear for my procedure.

[.offset]
+++[+++Previous to his embarking for America, he wrote to his wife as follows:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, Fifth Month 22nd, 1794.

I doubt not you will be desirous to know what I am doing.
I would have written you sooner, but waited till I should be able to inform you,
how my concern felt to the Yearly Meeting +++[+++of Ministers and Elders:]
and as it was laid before it yesterday, I may now tell you, that,
far contrary to what I had sometimes thought, it was generally approved of; and many,
very many Friends expressed their near unity with me;--so much so,
that it was indeed a humbling time to my mind:--may my heart be sufficiently thankful.
Through the unspeakable mercy of our dear Lord, who seemed so to cover us with His love,
that the living were knit together as the heart of one
man,--it was made a memorable time to many.
Dear Martha Routh opened her concern first, which helped me,
for indeed I was so overcome with fear and diffidence that I needed help.

I cannot tell you yet, which way I am to go, or when I may get away,
not having had full inquiry made +++[+++as to a vessel;]
but shall write you when the matter is fixed.--I am lodging at Miller Christy`'s,
a very agreeable lodging it is, the whole family are so affectionately kind:
they often speak of you with much respect.

The Yearly Meeting is very large, the new Meetinghouses,
both the men`'s and women`'s are quite filled;^
footnote:[The first year in which the present Meeting-houses were thus used.]
and it may be acknowledged,
that evident tokens of the Great Master`'s regard were to be felt:
yet I do believe we should be more eminently blessed with His presence,
if there were less of the wisdom of the creature
prevalent in our meetings for discipline.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Barbara Cruikshank.

[.signed-section-context-open]
London, 20th of Sixth Month, 1794.

To Barbara Cruikshank.

In love unchangeable I salute you;
in which I feel afresh united to you in spirit in the gospel covenant,
which covenant is love and life.
Though in our respective allotments, we may at times have to experience varied trials,
and in our measures a portion of suffering with the seed;
and often to go down into baptisms for the dead, as well as on our own account,
to prepare us by a stepping into the river of judgment,
to bring up our stones of memorial to the excellency of that Divine power,
which supports and keeps steady in the flood;
and which preserves in the faith and patience, in times of seeming desertion,
when we may be exceedingly hungry;
insomuch that the enemy may be permitted to tempt us to desire,
that the stones may be made bread.
Let us in these times remember our dear Lord`'s answer to the tempter,
"`that man shall not live by bread alone,
but by every word of God;`"--by every dispensation that the Lord in His wisdom sees
fit to bring us through:--this is food and drink to the truly devoted heart.
And however long a state of desertion may continue,
let us beware of forming any image or likeness
in His absence;--remembering +++[+++for our warning]
that when Moses remained long on the mount, the people adopted this language,
"`As for this Moses, we know not what is become of him;`" and they proposed to Aaron,
to make them gods to go before them.
Now this impatient spirit, the enemy takes advantage of;
and by his subtle transformations,
by presenting to the mind specious and pleasing openings,
and with attempting to create a desire to communicate these openings to the people,
suggesting that +++[+++the matter presented]
is something very suitable to their states, and may bring esteem to self.

All these things, my dear Barbara, are carefully to be rejected,
and the patient waiting kept in, for the return of the right thing +++[+++the Divine Anointing,]
which perhaps may come in, while the mind is under a feeling of great weakness;
and a cross +++[+++to the natural will]
will be experienced in stepping forward under this weakness.
May you ever bear in mind that the cross is the way to the crown;
and that all right ministry is exercised in some degree under the power of the cross,
and under a sense of +++[+++human]
weakness.
I believe you know that I am deeply concerned for your growth and preservation,
and feel a desire to open to your view,
some of the snares by which the enemy of our
soul`'s peace seeks to make us stumble and fall.
I write to you as a child;
and suppose you will not be unwilling to acknowledge yourself one.
Every crown must be cast down at the feet of Jesus.--O! may He preserve you,
and nurse you in the arms of His love; and enable you, under the influence of His Spirit,
to remember poor me, and to beg for my preservation.

--

I embarked at London on board the ship Barclay, bound for Boston, New England,
the 21st of Seventh Month, 1794:
I had the company of the following Friends as fellow-passengers, namely: Samuel Emlen,
who was returning from a religious visit to Friends in England, Martha Routh,
who like myself was bound on a similar errand to Friends in America,--William Rotch,
his wife, two daughters, and two female servants,
also four young men going with a view to settle in that country.

We cast anchor at Gravesend, where I went on shore and lodged two nights.

Seventh Month 30th. Have had calms and contrary winds since leaving the Downs,
we are now tossing about with the wind still against us;
but I have cause thankfully to acknowledge Divine goodness, in preserving my mind calm.
Samuel Emlen poorly, and weak in body, but animated and active in mind,
richly laden with good fruit, a little of which he sometimes scatters among us.

Eighth Month 1st. Passed the Isle of Wight with a fair wind; most of the passengers sick,
Samuel Emlen and myself excepted.
I have renewed cause of thankfulness,
in being able a little to assist some of the most neglected part of the sick family.
I feel fresh sympathy with the poor,
and long for more of the harmonizing power to prevail in our hearts; that we,
like our heavenly Father, might know no respect of persons,
from their higher or lower stations in life.
O my God! purify my heart more and more: qualify me to dwell with your pure seed,
even in suffering, if it may be the means of fitting me, in any degree,
as an instrument in your hand, to remove obstructions in the hearts of others.
O Lord, I thank you for a renewal of confidence in You;
and beg that you will be pleased to preserve me in your fear.

2nd. Had a tossing night; but today the wind is fair: pretty well in health,
but oh my leanness of soul: I seem the poorest of the poor.
I am ready to cry out,
Lord grant patience and preservation from taking flight in the winter.

6th. Last twenty-four hours very rough; wind continues contrary, but not quite so high:
most of the passengers sick; I am through mercy about as well as any of them.
My poor mind has been a little refreshed this morning,
being filled with calm resignation and thankfulness to the God of all grace,
inasmuch as He is pleased to sustain me in a degree of confidence in His mercy,
and in a willingness to conform to what He sees fit.
This morning I have felt renewed sympathy with the poor,
in observing the different situations of the sick in this vessel.
While some are attended with the utmost diligence,
and everything possible done to alleviate their sufferings,
others seem little heeded or felt for.
I am thankful that the Lord is pleased to afford me a poor creature,
the ability of rendering some little assistance to those who are neglected by others.
O my God! may the operation of your power more
and more purge from my heart and those of others,
everything that obstructs the pure unity, the prevalence of that undefiled love,
in which your creatures may, like You, be divested of respect of persons,
and which would produce uninterrupted harmony.
Who can sufficiently admire the extent of "`Your unparalleled love;
it continues even when we rebel against You;
for you strive with us to gain us to yourself, while we, ungrateful creatures,
can scarcely forgive the smallest fault; You forgive us all our great debt,
but we are not willing to abate one farthing.
O Lord! be pleased to humble us under a sense of your goodness and of our unworthiness,
and sanctify every dispensation to the purification of our hearts;
that we may be enabled to serve you more acceptably.

9th. Fair and moderate wind.--Our passengers have got over their sickness,
and look a little cheerful today.
We have seen many porpoises and one whale, a wonderful creature.--

[verse]
____
"`Marvellous are your works,
Parent of good Almighty:
Thine this universal frame, thus wondrous fair;
Thyself how wondrous then!`"
____

O! enable me still to put my trust in your name, and constantly to watch unto prayer,
that I may be preserved from the wiles of the enemy, who I feel is busy with me,
though speciously disguised;--and teach me to do your will, desiring nothing more.

11th. Distressed in spirit,
without knowing the cause,--unless it be sympathy with a dear youth,
in whom a considerable struggle is evident,
which of the two seeds shall have the victory:--strong natural propensities to vivacity,
require deep baptisms to subdue the efforts of the creature to preserve that life,
which ought to be crucified and given up, for the sake of Christ and the gospel.
O Lord! spare not, but let your power so operate, as to break the rock in pieces.
I feel at this time, through your mercy,
willing to suffer every dispensation necessary to prepare my heart to do your will,
and to enable me profitably to feel the state of the seed in the hearts of the people.

12th. Had two meetings yesterday, at one of which the captain and several of the sailors,
with the passengers not belonging to our Society, were present;
to whom suitable counsel was administered in some degree of gospel authority;
by which the hearts of several were affected,
and some of ours made thankful for the renewed favour.
A heart-tendering season, we had together in the evening among ourselves;
some deeply exercised state was felt with and spoken to with encouragement;
and yet after all, how pained and depressed do I feel today.
O Lord! grant patience: you know that I desire nothing but light to discover,
and ability to perform your will.

Last night, we were apprehensive that we were chased by three ships of war;
but this morning they are out of sight.
The wind continues fair, though but little of it; very pleasant weather.

13th. Wind fair and pretty fresh.
I have a headache, but my mind though poor, is, through mercy, pretty quiet,
and my confidence in the sufficiency of infinite Power and goodness is renewed:
may no instability in me, tend to lessen it.

18th. Wind fair today, after three days, in which it was strongly contrary.
Yesterday, I was very poorly with headache and excessive sickness; but,
through infinite mercy, was favoured with a sweet feeling of love;
in which I was enabled to pray for entire conformity to the Divine will,
during the remainder of my days.
In the evening I was a little better, and we had a meeting,
in which some instructive communication was handed to the seamen and passengers;
but my mind was grieved with the impure spirits and
corrupting conduct of some that profess with us.
I have mourned, since we came on board,
under a sense that such as these may pull down more
than the advocates of the gospel can build up.
But what can we say?
Lord! the work is yours: to you do we look.

23rd. For four days we have made very little progress, the wind, though moderate,
is directly ahead.
By the seamen`'s calculation, we are still 1800 miles from Boston.
Our passage is likely to be long; yet we have no cause of complaint,
but rather of thankfulness, as we all enjoy pretty good health, except Martha Routh,
who is sickly, and spends most of her time in bed.
Last night she was up, and we had a little religious sitting together;
when some instructive counsel, tending to encourage to faithfulness,
was handed to an individual.
The Lord was pleased to give a taste of his love;
if He graciously continue to do so from time to time, my soul will say, It is enough.

25th. A pleasant morning, but little wind; all well.
Had a favoured meeting yesterday: the Lord has not left us,
but frequently covers us with his uniting love,
giving renewed evidence that He is willing to draw near to those who
are at a distance;--thanks be to His ever worthy name.

29th. Calm yesterday and today, after a strong gale, which continued two days,
and brought on almost a general sickness among the passengers;
but now all are well again.
We were roused sooner than usual this morning,
by a report of a vessel making signals of distress;
on which account our captain lowered sail, and waited for her; but when she came near,
she was discerned to be a ship of war, and by her endeavouring to get to windward of us,
she was suspected to have some hostile design; some even feared she was an Algerine,
at which W. R., and one of his daughters in particular, were not a little alarmed.
Through mercy I was preserved calm, and enabled quietly to hope in God.
Our people hoisted sail and made away from her, upon which she fired several shots at us;
some of the balls were observed to graze the water very near us;
but the wind sprung up favourable, and we soon got out of reach of her guns,
and she then turned round.

Ninth Month 5th. Yesterday sounded, and found bottom 100 fathoms,
on the banks of Newfoundland.
This morning found bottom at forty-five fathoms.
Our people tried to catch some cod fish, but without success.
Saw several fishing vessels at a distance, and spoke one from Nova Scotia:
they offered us some fish, which our captain at first declined,
and made another attempt to catch some; but as he did not succeed,
our mate and two sailors were sent in the little boat
with a present of some rum and porter for the captain,
who in return, sent us thirty-five large fish;
upon a dozen of which we all dined heartily.
We have much contrary wind, and get on very slowly,--sometimes rough weather,
but not what the seamen call a storm.
Last night we saw very near us a mountain of ice,
similar in size and appearance to a large old castle.
The seamen say it is common to see such masses floating here;
and sometimes in dark nights, ships strike upon them, and get damaged.
We are supposed to be 1000 miles from Boston.

8th. We have had a fine run, the seamen say 300 miles, in the last two days.
This forenoon, a hard gale of wind; the dead lights were put in,
and we tumbled about the cabin from side to side; but the wind suddenly turned,
and it soon became quite calm.
Had two meetings yesterday, in which some degree of good was extended,
particularly to some of the blacks belonging to the vessel,
who were present in the evening.

11th. All well.
Contrary winds continue;
for the last two days we have been in what is called the Gulf Stream.
The sea is nearly as warm as new milk, occasioned, it is supposed,
by a stream flowing out of the Gulf of Mexico, forced along by the trade winds.
We spoke a ship today from America, bound for Liverpool, by which we sent some letters.
We are supposed to be about 500 miles from Boston:
three or four days of fair wind would now bring us there, but that is in the Lord`'s hand;
may He grant patience to wait His time.
We have had meetings constantly on Fourth days, and twice on First days:
the Lord has not failed to be with us, blessed be His name!

12th. A perfect calm;--not the smallest progress, but through mercy all well.
Several of the passengers, who could swim, went overboard to bathe.
My mind renewedly entreats preservation in exact conformity to the Divine will.

14th. All well; wind fair; 320 miles from Boston.
Our meeting very poor, though I believe some were favoured with a renewal of strength:
Samuel Emlen and Martha Routh had considerable communications to the youth;
but dryness and barrenness were my portion.
Lord! grant patience.

Yesterday, I was favoured with the reading of Martha Routh`'s memoranda of the voyage,
which had a humbling effect upon my mind.
The many instructive remarks tended to open to my view my own extreme barrenness.
A sense of my unfruitfulness often makes me conclude,
that so poor a creature was never before sent on such an errand;
however I am sometimes a little encouraged by recollecting,
that where little is given little is required.
I mourn deeply that so much labour bestowed on some of our young people,
seems to be in vain.
May the Lord meet with them in a narrow place.

15th. Very languid today, rheumatism in my legs: yet through mercy my mind is calm,
and renewedly centred in the one desire,
to be favoured to know and enabled to do the Divine will.

Last evening, in meeting had a depressing time, in sympathy with the thirsty travellers.
Towards the close was a little relieved by the communication of a few encouraging hints.

19th. All well, but progress slow; wind mostly contrary.
Have spoken with two vessels from Boston today, and find by their account,
that our desired port is more distant than we expected

On Fourth day, we had a very solemn meeting, a memorable time of favour;
for which reason some of our company were ready to conclude it
would be the last which we should have on board:
for my part, I am too blind to foretell anything, but through mercy feel resigned.
Many small land birds came on board today,
some of which our people caught and put in a cage.

21st. Had a comfortable meeting, my mind renewedly covered with love and thankfulness,
that the Lord has not forsaken us.
Martha Routh reminded us, to our comfort, that "`They who trust in the Lord,
shall never be confounded;`"--adding a few remarks encouraging to the youth:
with some of this class I feel a close spiritual union,
which I believe to be gospel fellowship.

Yesterday spoke two vessels,
the captain of one kindly offered some apples for our female passengers.
Our captain sent the boat with a present of some porter,
and brought us in return a basket of apples, with some vegetables,
on which we made a pleasant repast.
A poor little cat accidentally fell overboard:
we were affected by seeing the poor creature drowning,
and one of our young men wrote an elegy on its death.

22nd. Yesterday we were within sight of Cape Cod; but the wind continuing adverse,
we have made very little progress.
We are supposed to be within twenty miles of Boston,
but there is no prospect of getting there without a change of wind.

We had our meeting as usual yesterday, in which several communications were offered;
and we were favoured with a renewed evidence of the continued extension of Divine regard.
My mind was introduced into a feeling of deep sympathy with an individual of our company,
who, I apprehend, is suffering under discouraging fearfulness,
so as to prevent a full obedience to the manifestations of truth.
My secret prayer is, Lord! you who know all our weaknesses,
be pleased to extend help to your little ones,
and increase our faith and confidence in your power.
