== Chapter IV.

His Travels In America Continued--Returns Home in 1797

+++[+++From Philadelphia John Wigham journeyed towards New York, holding several meetings;
among which he mentions, Almswick and Colebarrack, as affording a pleasant prospect,
from there being a number of religious young people, and some under convincement;
particularly at the former place, where he says, he had a comfortable silent meeting.
Leaving New York, he proceeded to Flushing; where, and at some other places,
he had meetings; and returned again to that city.
His manuscript, at this part supplies no dates,
but continues with the following remarks:--]

Friends in Long Island seem to me to depend too much on the labours of others,
of which much has been bestowed, for they have several able ministers among them;
their desire to hear preaching makes them wait for it,
thus neglecting their own exercise; so that though very plain in appearance,
their attainments in religion, are, I fear, but small.
They are trusting too much to the form:--may the Lord break their false rest,
and give them to see the danger of such a state.

From New York I went to Rahway and to Plainfield, to attend the Monthly Meeting.
The case of a Mulatto woman, who had applied for membership with Friends,
came before the meeting: a committee had been appointed to visit her,
and reported their satisfaction as to her convincement;
but thought it unsafe to receive her on account of her colour!
After much discussion,
it was at last concluded to refer the matter to the Quarterly Meeting.
How hard it is to overcome old prejudices.

Proceeded to Squankim, Little and Great Egg Harbour, and several other places,
to Philadelphia, where I attended meetings on First day; and on Second,
accompanied by my beloved friend Samuel Smith, also Ebenezer Cresson,
and several other Friends, I went to Plymouth, Providence, and Potsgrove;
where I parted with all my companions, except Ebenezer Cresson, who continued with me,
and we had meetings at a number of places.
On our way to Milesburgh, up the river Susquehanna,
we passed through a very pleasant valley, among good land for about thirty miles.
There are none of our Society at Milesburgh; but Richard Miles, the founder of the town,
entertained us kindly, and we had a satisfactory meeting on First day.

Second day, rode to Halfmoon Valley, to a Friend`'s house;
had a meeting next day at Warrior Mark Valley,
where there is a considerable settlement of Friends; it was comforting and encouraging.
We next lodged at Daniel Pennington`'s, and had a meeting at his house;
then went sixty miles to Dennis`'s Creek, a wilderness journey,
in many places only a foot path, and that a very rough one;
but we were favoured to get along safely to William Conworthy`'s,
where we were kindly received; the family, which is a pretty large one,
have the mark of discipleship.
We attended their meeting on First day; on the following day,
had a meeting in Bedford Court House; after which, rode back to William Conworthy`'s,
attended their meeting on Fourth day, and then proceeded to Miller`'s Tavern,
among the Alleghany mountains.

The next day`'s ride was twenty-six miles to James M`'Grow`'s;
then attended Soweekly meeting; and so to Providence, Fairfield, and Frankford.
We have had a long journey through woods and wilds in abundance,
yet not without some satisfaction;
though many of these settlers are very ignorant of what they profess:
yet the Lord is in mercy following them, and some are listening to His voice.
May the visitations of His love prove effectual for their gathering unto Christ,
the true Shepherd.

Went from there to Fallowfield and Westland, where we met with an ancient friend,
Zachariah Farrington from Wilmington; he seemed to enter into the state of the meeting,
and had considerable openness in communication, but it did not relieve me.
At the close of the meeting I gave intimation,
that I thought of attending their next week-day meeting; so I went to Redstone,
and returned to Westland, and on to Centre.
The Redstone settlement, as this Monthly Meeting is called,
seems to me to have more of the form than the substance; however,
when I consider that most of them who generally come here,
are wanderers from mere worldly motives, without regard to the honour of Truth,
I admire the goodness of a gracious God in following them.
Some are brought under a right concern,
and seem to be deeply sensible that the seed of
the kingdom is depressed under a worldly spirit.
May the Lord strengthen them

I next went to Union and Sandy Creek-Glade, over the Laurel Hills;
so crossed the mountains to Frankford, sixty-one miles, where I had a meeting;
none of our Society living there: had meetings also at Banegarden,
and a number of other places.
At Lampeter the weekday meeting was very small,
and I have reason to believe that great deficiency in the attendance
of weekday meetings prevails among Friends in these parts;
a worldly spirit is too prevalent among parents, who, though they attend themselves,
leave their children at home employed about their business,
and thus neglect the spiritual interests of their precious charge.
On this account I often feel sorrowful,
and am frequently exercised in close labour with them.

Proceeded to Robert Moore`'s at Sudbury, who with his valuable wife received us kindly;
and their precious daughters seemed to have
pleasure in performing many kind offices for us.
I felt so weak and unworthy, that I had not faith to have a meeting appointed for me;
so I stayed two days to attend their First day meeting, which, through merciful help,
proved a reviving and strengthening time.
Taking a few more meetings on my way, I arrived at Philadelphia,
to attend the Yearly Meeting.

I can do no less than commemorate the Lord`'s goodness to me; for though often very low,
and in my own eyes the most unworthy servant ever sent on such an errand,
yet the Lord has graciously helped me along from place to place;
and though I cannot record extraordinary times of favour in meetings,
which some have enjoyed, yet I trust the cause, though weakly supported,
has not been dishonoured.
I humbly thank my God, that he has, from time to time,
renewed faith and strength to endeavour to do what I apprehended to be his will;
nor do I at this time ask for more than light to see, and ability to perform it.

24th of Ninth Month, 1796.
The Yearly Meeting which commenced this day was graciously owned,
and I hope it proved a profitable time to many.

To Ann Christy.

Philadelphia, 24th of Ninth Month, 1796.

I am come here to attend the Yearly Meeting,
which begins today.--I have had a long mountainous journey this summer,
in a newly settled country, over the Alleghany mountains;
and through favour have got along pretty well:
the weather has not been so oppressively hot, as in the preceding summer,
and consequently I am not so much reduced, and feel pretty well in health.
I must acknowledge I serve a good Master; who, notwithstanding my many weaknesses,
condescends to be a present help in the needful time.
I can write encouragingly to you, to dedicate your heart and all to Him,
and to serve Him faithfully in the way of His
requirings:--He will be your helper in every trial.

After the Yearly Meeting at Philadelphia was over,
I proceeded to the Yearly Meeting at Baltimore, accompanied by Ebenezer Cresson,
his precious sister Sarah, and Catherine Haines, in a carriage;
taking several meetings by the way.
The Yearly Meeting was satisfactory,
as were also a meeting on First day morning at Baltimore;
and one in the afternoon appointed for the black people.

Had the company of the aforesaid Friends to three meetings.
At West Nottingham, I parted with Sarah Cresson, and Catherine Haines,
and accompanied by Ebenezer Cresson, went to East Nottingham,
Sassafrax and several other meetings;
they were small as to those professing with Friends,
but the neighbours of other religious societies attended,
so as nearly to fill the houses;
and strength was afforded to minister to those assembled.
A few solid Friends remain in those parts,
but their number has greatly decreased of late years; and from this cause,
several of the meetings seem likely to be discontinued.
We were refreshed both in body and mind, at the house of Susanna Matthews, widow,
who delights to wash the disciples`' feet; may the Lord reward her labours of love.

+++[+++It appears he was at New York in the Eleventh Month, 1796,
from which city he addressed a letter.--]

To His Daughter, Jane Cruickshank.

New York, 6th of Eleventh Month, 1796.

You have so often been the companion of my mind,
in something like a sympathy with yours in conflict,
that I feel willing to tell you my belief, that it is the Lord`'s way of working,
to prepare the ground, to make it productive of fruits to His honour,
to turn and overturn it, and burn up the weeds.
Now, my dear child, do not be too much discouraged under the operation,
or think when you are plunged into pits, that you will never get out again.
I know there are dispensations to pass through,
during which we can discover no profit that can arise out of them,
because of the darkness that surrounds; but when the light again breaks forth,
we can say, the Lord`'s way is a great deep,
and in it marvellous mysteries are discovered.
May your trust be in Him, and your heart devoted to Him; and He will never leave you.
My dear John, your beloved husband, will I trust be a true helpmeet,
and that you will be travellers together, take sweet counsel together,
and go up to the house of God in company;
and unite in giving the preference to the Lord`'s work
and service at all times and on all occasions.
I know the advantage of such a union;
your mother and I were united in desire to serve the Lord, above all and before all;
and in this union we were often concerned to encourage
and strengthen one another in dedication of heart.

Your dear John`'s letters I have received; he seems to think I am slack about writing;
but he mistakes, in these remote places where I have been,
there is rarely any opportunity of conveying letters; Friends are scattered very wide,
and far back in the woods.
There are also many people of other societies in similar situations,
whom the Lord seems to be peculiarly visiting:--many
have been added to our Society by convincement,
especially in these back settlements, and several have requested to be received,
who are situated several hundreds of miles from any settlement of Friends.

As to the time of my return, you must keep in the patience; give me up freely,
and pray for my preservation.
If I am but favoured to finish well,--no matter when or where.
I never felt more love to you all;
yet I believe it best to resign you to the keeping of the Shepherd of Israel; believing,
if you are faithful to Him, He will keep you.

+++[+++About this part of his travels,
John Wigham gives a list of a number of places at which he had meetings;
he also states having attended the Quarterly Meetings at Concord and London-grove,
which were large and satisfactory.
Arriving at Philadelphia, he says, "`I attended the meetings on First day evening,
and Second day morning, and the North meeting on Third day; then crossed the Delaware,
and rode to Joseph Whitall`'s,
who with his wife received us kindly,--a sweet young couple, fellow travellers in spirit;
my mind was refreshed in their company.`"
No dates are supplied here.
He afterwards enumerates thirty-one different places which he visited,
and came again to Philadelphia.
The two following letters appear to have been written during this interval:--]

To Barbara Cruickshank.

Hockeson, Pennsylvania, 16th of Eleventh Month, 1796.

I received your acceptable lines about two weeks ago.
Your sweet sympathetic remarks were truly reviving,
and no part of your letter was more pleasing,
than your sensible acknowledgment of your feeling of weakness,
and your desire of continuing under the refining power.
It is an inexpressible mercy to be preserved sensible of what we are,
and in whom is our strength; turning our attention to, and placing our dependence upon,
the supporting Arm of power.
I desire to be your companion in watchfulness and fear;--
"`the fear of the Lord is a fountain of life,`"
preserving from the snares of death.

I am here hobbling along as usual: you know I am a poor weak creature; but I may say,
in humble thankfulness, the Lord has hitherto helped me;
so that I trust I have been preserved from
bringing dishonour on the cause I have espoused.
I cannot tell you much about the time of release from this country,
though if no new concern open,
perhaps I may get through the prospect now before me this winter;
I sometimes look at reaching the next Yearly Meeting in London.

[.asterism]
'''

To His Wife.

Philadelphia, 15th of Second Month, 1797.

I received my dear Eliza`'s acceptable letter, dated the 3rd of Eleventh Month,
after a long time of waiting in suspense; the date of your last preceding one,
was in Seventh Month.
Whether you have been so long between writing, or some letters have miscarried,
I know not, but I thought the time very long.

I am here, through favour, pretty well in health.
I expect to leave this city on Sixth day,
to attend three Quarterly Meetings in the Jerseys,
and hope to be clear to leave this place after the Spring Meeting,
which is to be held the latter end of next month.
I am looking towards the Yearly Meeting in London; but a prospect sometimes presents,
though not yet with clearness, and whether it may die away or revive when the time comes,
I believe it is best to leave, and stand resigned;--this prospect is Nova Scotia,
which if it should be visited, will prevent my getting home,
(if spared to do so) till the fall of the latter part of summer.
I wish to stand resigned;--the Lord has hitherto
helped;--His goodness I must acknowledge,
whatever becomes of me:
I cannot offer Him less than full dedication and obedience to
what He clearly discovers to be His requiring;
and I have a belief that He will not condemn for omission,
when the matter is not made clear.
I feel for you and sympathize with you in your exercises, which I know have been many;
but my dearest, seeing we unite in acknowledging the Lord`'s goodness,
let us continue to put our trust in Him, and follow on to do His will,
as well as we know how.
Our pilgrimage is passing over,
it will not be long;--let us keep the recompense of reward in
view;--if we can only attain to a quiet habitation at last,
all these conflicts will be forgotten.

Here (at Philadelphia,) I attended meetings almost every day,
and in company with Martha Routh, visited twenty-four schools,
and had some satisfactory times with the children.
Attended Abingdon Quarterly Meeting, and returned to the city.
Paid a comfortable visit to eighteen young women,
who had formed themselves into a society for the
education of black girls--they take it by turns,
two or three at a time, and teach them reading and writing,
from six till nine o`'clock in the evening: they have about seventy scholars,
chiefly grown up.
Visited another society of young women, twenty-five in number,
who make it their business to search out and relieve the poor: they beg from the rich,
some of whom give liberally;
and in this way they distribute several hundred pounds a year.
They meet once a week to settle their accounts, and confer together about objects.
I was with them at one of their weekly meetings, much to my satisfaction.

Left Philadelphia to attend the Quarterly Meetings of Woodbury, Bucks, and Burlington;
and then returned to the city,
and attended the Spring General Meeting +++[+++of Ministers and Elders,
and three Monthly Meetings which succeeded.

To Ann Christy.

Philadelphia, 4th of Fourth Month, 1797.

I feel unfit to stain much paper with the pen, yet to you I think I can do a little,
when I remember your solicitude about me,
and expression of a hope of seeing me at the Yearly Meeting +++[+++in London.]
These lines may let you know that my views are turned another way.

Yesterday, I took a passage in a vessel bound to Charleston, South Carolina,
and from there I have a prospect of proceeding to Nova Scotia, if way open.
It has been a pretty close trial to turn my back on home,
after having entertained some hope of being released from further labour in this land;
but through favour I have been enabled to say, "`Your will be done.`"
Two Friends from this continent, Charity Cook, and Mary Sevett,
have a prospect of going over to England to visit you, and expect to sail in a few weeks.
Martha Routh expects to leave this city in a few days, to go to Long Island,
and to New York, and Rhode Island Yearly Meetings.

Your attention I take kind: I believe it is love in your tender mind to the Great Master,
that makes you willing to serve the servants, how little worth soever they may be;
and verily I often think, none can be more unworthy than myself:--however,
I have no disposition at present to complain; I must acknowledge that the Lord is good.
May we be enabled to keep our eye single unto Him, and lean upon Him;
this will meet His acceptance.

Fourth Month 6th, 1797.
Left Philadelphia, and embarked in the brig Maria, Captain Strong, for Charleston,
South Carolina, with my former companion Ebenezer Cresson.
It was a disappointment to me to have to turn my back on home,
after hoping that I should have been released from further labour on this continent;
yet when the Lord gave a clear prospect, He also gave faith.
Praised forever be His holy name!

I now enjoyed a mental calm,
attended by an evidence that the Lord continues to be all powerful,
and that His power makes His people willing.^
footnote:[At this period John Wigham appears to have been brought under close trial.
He had sometime before apprehended that way was opening for him to return home,
and he had given his friends and near connections some expectation,
that he might arrive in time to attend the Yearly Meeting in London in 1797;
and in anticipation of this being the case, his beloved wife went up there,
hoping to meet him, but was, of course, painfully disappointed.
When, however,
he became fully convinced of the Divine requiring for farther gospel labour in America,
he evinced his dedication to the cause he had espoused,
by yielding thereto in simple obedience.
In allusion to the subject, he says in a letter to a Friend,
"`through favour I have been enabled to say,`'--"`Your will be done.`"]

Fourth Month 7th. In the river opposite New Castle.
Lord! you know what a poor creature I am;--my trust is in You;
O! keep me in your pavilion.
You are my stay, gracious God! while floating on this unstable element;
for which I humbly thank You.
O! enable me faithfully to fulfil the embassy on which you have sent me!

14th. Passed Cape Hatteras with a fair wind, all well,
though we have had two tossing days and nights, occasioned by a strong south-west wind.
I have been a good deal tried by the apparent carelessness of the Captain,
not that I feel much anxiety about my own life;
but I have been uneasy about dear Ebenezer,--
having been the cause of his taking this voyage.
I had little sleep last night, but feel peaceful and quiet this morning.

15th. Have had a roughish sea since yesterday,
and last night nearly ran upon Look-out shoals.
I lay awake all night, and could not banish fearful apprehensions about my dear Ebenezer,
and the distress of his mother and sisters, should any accident happen to him;
but the innocent youth himself slept sweetly.
We are among as wearing crew, the Captain particularly; though alarmed last night,
he cursed terribly.
"`If the righteous scarcely be saved, where shall the ungodly and the sinner appear.`"

16th. Last night very stormy, thunder, lightning and rain,
made more awful by the darkness.
The sailors say they never saw a more dismal time.
A squall of wind ensued, and it was very rough.

17th. Calm and fine now, after the rolling.
We see many wonders as well as changes.
I think of all the men I ever saw, our Captain is the most hardened and desperate,
though civil and obliging to us.

Landed at Charleston on the morning of the 20th; stayed there over First day,
and had two meetings.
Here are a few, who call themselves, and are called by others Friends;
but alas! the name is all; they seem completely united with the world.

To His Daughter Jane Cruickshank.

Charleston, South Carolina, 21st of Fourth Month, 1797.

Though we are far, very far separated,
yet I frequently feel a near sympathetic union with your spirit,
and renewedly so at this time; and as there is an opportunity from this place,
by a ship expected to sail for London in a few days,
I thought I might tell you what revived in my remembrance,
in my looking at you and feeling with you;--even the prophet`'
s expressions respecting the blindness of the Lord`'s servants,
and how He leads them in a way that they neither have heretofore known, nor yet do know,
yet He makes darkness light before them--smooths
and makes straight their rough and crooked paths,
and promises that all these things He will do for them, and not forsake them.

Various indeed are the dispensations,
through which the Lord sees it needful to bring His chosen servants,
preparatory to the production of acceptable fruits unto Him;
yet He never fails to sustain and help those, who put their trust and confidence in Him,
and who give up the will to Him, excluding self,
and watching and warring against it in all its varied appearances.
My spirit salutes you, and bids you fear not;--hold fast your confidence,
and keep on your way in the littleness`';--O! the littleness, how beautiful and how safe!

[.asterism]
'''

To Ann Christy.

Charleston, South Carolina, 21st of Fourth Month, 1797.

I arrived here yesterday, having had a passage of two weeks from Philadelphia;
in which we met with contrary winds, thunder, gusts, and squalls;
but we were preserved through all; and neither my companion nor myself sick,
which I esteem a great favour.

We have made a sudden transition from winter to summer,
everything here is in full bloom, green peas in perfection, peaches half grown,
and figs just setting.
How my poor tabernacle will stand this hot climate I know not, it is now very warm.

There are very few in this city that profess with us, though they do keep up a meeting:
the family where we are lodged, received us kindly; though except the man Friend,
the rest of the family were dressed in high French fashion.
It appears to be a place of idleness and dissipation,
the white inhabitants being supported by the labours of the slave; indeed,
it may truly be said, these southern states are a land of darkness,
darkness that may be felt; and yet in this thick darkness,
the people are boasting of light and liberty; a miserable mournful situation,
pride and oppression abounding.
I do not want to hurt your feeling mind, dear Ann, with such things;
but the subject somehow has stolen my pen.

Now turn your thoughts.--Though darkness cover the earth and gross darkness the people,
the Lord continues to be a light to those, who know their dwelling to be in Jerusalem,
the quiet habitation:
there is still light in Goshen;--the Lord is a sanctuary to his people,
and will be the preservation of all who trust in Him.

I do not know that I have much more to say, having written you so lately;
but I desire my love may be communicated to Friends,
leaving the particulars pretty much to you.
You know I love them that love the Truth, and I know you do so likewise.
We love one another, and in that reciprocal love, may we experience a growth;
which no doubt we shall do, as we continue to watch and war against everything,
that would obstruct the precious spiritual union with the Father and the Son,
in whom is the life.

Second day.
Set out towards Wrightsburgh, in Georgia;
reached a Friend`'s house at a place called Eddiston,
where we had a meeting with a few Friends, who live in the neighbourhood.
Hence proceeded without any other meeting to Wrightsburgh,
a long weary journey of about ninety miles.
My horse became foundered, so that we were obliged to leave him;
and not being able to procure another, my companion and I had only one horse between us,
and we were consequently, obliged to walk by turns most of the way.^
footnote:[During this part of his travels,
although John Wigham has not left any record of it,
a circumstance of a very trying nature occurred,
which he has frequently related to some of his friends;
the particulars of which as near as can be recollected,
were the following:--His companion and he, having, as before stated,
only one horse to carry themselves and saddle bags, rose early in the morning,
and travelled till about ten o`'clock, when they stopped to breakfast.
They had only just commenced their repast, when an alarm was given, that their horse,
which had been put into the stable, but not tied up, had run off,
having as was thought followed some other horses, that had been passing.
John Wigham, his companion, and some other persons, immediately set out in pursuit,
following him into the woods.
They were not long in finding him, for in crossing a piece of boggy ground,
the horse sunk down into it so completely, that all the exertions of the party,
continued for several hours, failed in extricating him.
Towards afternoon, John Wigham, having become faint from fatigue and lack of food,
lay down on the ground, in sorrow and perplexity.
While lying in this exhausted condition, it occurred to him,
to have small branches cut from trees, and trodden down into the bog,
just before the horse`'s head.
His assistants, on his suggesting it, adopted this plan,
until they had formed a pretty firm footing near the animal`'s fore-feet:
they then excited him to a fresh effort,
when he speedily raised himself on the platform thus prepared,
and to the great relief of John Wigham and his companion,
came out without having sustained any injury;
thus enabling them to pursue their journey.]
At Wrightsburgh, we lodged at a Friend`'s house, and got another horse.
Visited all the meetings in Georgia and South Carolina, and returned to Charleston,
383 miles.--Had a public meeting in the Council Chamber above the Exchange,
a large place, and pretty well filled, chiefly by men of the upper rank;
who behaved as well as I expected,
considering the fear they seem to feel with respect to their slaves.
The doctrines of Christianity are so opposed to their practice,
that it is hard for them to hear the Truth declared.
However, I was favoured to get through to some satisfaction,
without meeting with any public opposition; though I sensibly felt an opposing spirit.
My gracious Master took away fear, and enabled me honestly to deliver what was given me;
for which I feel thankful.
At the close of the meeting, some of the Methodists, particularly a preacher,
came and offered their meeting-house to accommodate the people of colour.
As I had felt drawn towards a meeting with that people, I accepted the offer:
the Methodists also undertook to give notice that the
meeting was to be held on First day morning.

Seventh day, 27th. While pensively sitting upon a bank over against Charleston,
(which appears to have been at some former period east up as a
fort,) I felt deeply sensible how poor a creature I am;
and was much humbled on this account.--Lord, you know my dependence is on You;
O! forsake me not, for your mercy`'s sake!
Though I am nothing, and worth nothing; yet as the honour of your cause is at stake,
O! be pleased to grant strength and preservation.

28th. The meeting was held as appointed; it was large, and through merciful regard,
an open time.
A great number of the black people attended, and were sober, attentive,
and many of them tender.
Attended Friends`' meeting in the afternoon, which proved a laborious time.
Through favour I was enabled to deal plainly with them,
and honestly to tell them the danger they were in;
believing that several of them were stumbling blocks, instead of way marks.
After meeting my mind was relieved of a heavy burden, and I felt easy to leave them.

Next day, about eleven o`'clock, embarked on board the Mercury, Captain Rease,
bound for New York.

Sixth Month 1st. In the Gulf stream, most of the passengers sick, myself not far from it;
though dear Ebenezer and I are about as well as any of them.

I esteem it a singular favour that my mind has been employed
in contemplating the goodness and greatness of God;
but the longer I live, the more I see the imperfection of man`'s finite conception,
and his liability to err.
God is truly an incomprehensible being; I feel Him to be Love, Life, and Power.
I perceive that, as to my own experience, He sometimes withdraws,
and sometimes makes himself manifest: when He withdraws, all is void and empty;
when He returns the soul is filled.
Yet even in these seasons, when He seems to veil himself,
His invisible power supports and calms the mind in quiet resignation;
and while there is an earnest desire or breathing for His return,
the life and regular frame of the soul is preserved:
but if these earnest desires are suspended, the frame is disordered,
and the spiritual health impaired; and hence arises the necessity of watching.
O! what care ought to rest on the mind of a minister, to deliver nothing as doctrine,
but what he receives afresh in the opening and vision of the Divine Light.
O Lord! preserve me!--my dependence, you know, is on You alone.

2nd. At four in the afternoon, rose from my bed sickly: have had a rolling night,
but the wind is now fair, and I hope we may not have a long passage.
The company we have, is by no means desirable; it is a strange mixture, an old captain,
a dancing-master, and a Methodist preacher, with his family.
Lord! help us to walk among them with consistent steadiness,
as becomes followers of Christ.

4th. Off the Capes of Virginia.
Moderate weather, and all well.

5th. All well.
About thirty miles from Sandy Hook.
We have got a pilot on board, and hope to reach New York tomorrow.
We are tired of some of our companions, though they have all behaved respectfully to us,
except on one occasion, in conversing about the slave-trade and slavery,
when a temperate vindication of the rights of the oppressed Africans,
drew forth violent and profane language from some of them.

6th. Arrived at New York: next day attended meeting.

8th. Sailed for Newport, Rhode Island;
where we arrived on the 11th. Attended the Yearly Meeting; after which,
rode to New Bedford.
Attended First day meeting, and the Monthly Meeting on Third day.
Seventh day embarked for Nantucket, and arrived the same day.
Attended their meetings on First day; also their Quarterly, Monthly,
and week-day meetings.
Returned to New Bedford, and attended First day meetings.
Seventh Month 3rd. Set out towards Nova Scotia,^
footnote:[It appears by one of his letters, that in this journey,
besides his former companion Ebenezer Cresson,
Joseph Wing a Friend in the station of an Elder, was also with him.]
took several meetings by the way.

To Barbara Cruickshank.

Portland, 10th of Seventh Month, 1797.

I know it is pleasing to converse in this way with those we love;
and I think it may be lawful and right to indulge in this pleasure,
even when we have nothing to communicate but common things;
as it has a tendency to sharpen, as iron sharpens iron,
and to revive in our remembrance those endearing sensations,
which have been formerly experienced in a participation of that uniting love,
which flows from the pure fountain; and of which you and I, in our measures,
have been mercifully made partakers.

I expect by this time you have experienced some plungings,
preparatory to the reception of stronger meat than that,
with which children are generally fed; and possibly some dispensations may be allotted,
similar to those,
concerning which the Apostle encouragingly +++[+++exhorts the
believers]--"`not to think it strange,
as though some new thing had happened to them.`"
Dispensations for the trial of our faith, which is more precious than that of gold,
are needful for our deepening in the root, and growth in experience;
as well as to prepare the heart for a more plentiful production of good fruit.
Well, my dear friend, I believe we cannot do better than keep in the patience;
for I think there is not a more necessary part in the composition of a Christian,
than patience; and if we add to it humility, self-nothingness,
and a simple dependence on Divine power, the enemy cannot hurt us much.
We have abundant promises to encourage us to seek and pray for this frame of mind;
and I believe it may, through watchfulness and care, be measurably dwelt in.
May we, dear Barbara, never cease striving, till we have attained.

I am here on my way to Nova Scotia;
and how long I may be detained in this country I know not:
there are but few Friends in these parts,
but my concern is pretty much for those of other societies.
It is likely to be a long journey, and I suppose from what I have heard,
rather a difficult one, through a country that has not been much travelled in.
Persons going to Nova Scotia mostly go by water;
but I seem most easy to try to get through by land,
my mind being drawn to a scattered people among the bays and lakes, which,
I am informed abound in that country.

At Broodcove had a meeting with some newly convinced persons,
to our comfort and rejoicing:
twelve have been received into membership with Friends since I was there before;
and several others appear hopeful.
We visited some persons of a similar description at Camden; then went to Belfast,
where I had a satisfactory meeting in a Presbyterian meeting-house.
The whole were quiet and attentive, and some appeared tenderly impressed.

We found that a member of our Society had appointed a meeting at his house,
seven miles from Belfast, to which we went: the people in the neighbourhood attended,
but they seemed very wild and uncivilized.
The Lord enabled me to declare the Truth among them,
but it seemed to make very little impression.

We rode as far as Pleasant River, without having any meetings;
though I passed through some settlements where my mind was attracted,--as I
thought the people were like sheep bleating for the shepherd:
but I did not feel a sufficiently clear commission to appoint meetings; so passed on,
rather expecting to return the same way.
Here we left our horses, and hired a boat to take us to a place called St. Andrews,
about eighty miles distant, in the British dominions.
We arrived there on First day morning, and appointed a meeting for the same afternoon,
to which a good many of the inhabitants came.
On Second day, took a boat to Beaver Harbour; got there on Third day morning,
and were kindly received by Ellis Wright: he had been a member of our Society,
but had gone out in the war.
He told us of some families of professors, about three miles back in the woods;
we walked there, and found several descendants of Friends,
and some who have a right to membership; with whom and their neighbours,
we had a satisfactory meeting.
They were glad of our visit, which was certainly a merciful visitation.
They informed us of a family nine miles further back;
of which the wife and nine children were members, the husband had been disowned.
We walked there, and had a comfortable meeting with them and their neighbours:
some of the latter, expressed much satisfaction.
We returned to Beaver Harbour,
and hired a small boat to take us to a place called St. John`'s, fifty miles distant;
where we arrived on Seventh day, the 29th.

Next day had a meeting in the Methodist meeting-house.
Second day, went in the post-boat seventy-five miles up the river, to Richard Mead`'s,
and had a meeting in his house: from there to Frederickstore,
where I had a meeting in the Court House, and returned to Richard Mead`'s. First day,
had a large meeting in a barn.
Second day, one at Benjamin Burdsel`'s, and one at A. Carpenter`'s;
then went on board a small vessel,
and down the river to St. John`'s (so called.) The people in
this country are chiefly refugees or disbanded soldiers,
to whom land had been given at the conclusion of the American war.
Some of them were descended from Friends, and several of their families are grown up:
they know something of the principles of Friends from books belonging to their parents,
or which, perhaps, were sent to them from some of their connections;
but they have no good example from their parents, and no associates,
but such as adopt the vain customs of the world.
They have generally joined their neighbours in these things, and also in their worship;
yet they seem to feel that they still lack something,
and are like sheep that have strayed long and far: they miss the pasture,
and bleat for the Shepherd; yet though He calls, they do not follow Him,
and so remain estranged from both the flock and the fold.
I was well satisfied with being among them,
and trust it may be a means of showing them the real principles and practice of Friends.
Of late many preachers, some called New Lights, and some Methodists, have visited them,
and have persuaded some that they do not differ from Friends, except in non-essentials;
and by their activity in singing, preaching, and praying,
have prevailed on some of these scattered people to join them.
We met with a kind reception, not only from such as have some connection with our Society,
but among all ranks; and I trust have been mercifully enabled so to move among them,
as to leave the door open.

At St. John`'s (so called,) we found a vessel just ready to sail, in which we embarked,
and landed next day at Anapolis.
Walked seven miles to Job Young`'s, where we had a meeting, and another next day,
(First day), at Samuel Moore`'s;
from there rode on hired horses one hundred and five miles to Halifax.
Here we left our horses, and crossed the bay to Dartmouth,
where there is a small meeting of Friends.
This we attended, and also visited their families;
but alas! they seem too weak to hold a meeting with reputation:
they have so far given up our testimony against a hireling ministry,
as to allow an Episcopalian minister to preach
in their meeting-house on First day afternoons.
From Halifax we rode to Anapolis, having several meetings on our way there,
and one there to good satisfaction.

+++[+++By the date of a letter to a Friend in England,
John Wigham appears to have been at Halifax, on the 19th of Eighth Month,
probably at this second time;
as he mentions his prospect of being at liberty
to leave America about the Tenth Month following.
With his usual diffidence and humility, he mentions his own labours in this letter,
nearly as follows:--"`I have been for some weeks where no Friends live,
and have had a good many meetings among the people.
There seems an openness to hear and acknowledge the truth,
and some of them are tenderhearted; beyond this I cannot say much.
I cannot fix much hope of good being done by such a weak unworthy instrument;
but the desire of my heart is, that if I can do little for the cause,
I may do nothing against it.
Satisfaction and peace sometimes flow in my mind,
in endeavouring to do the little committed to me honestly,
believing that the Lord does not require more than He gives.`"]

Went to Digby by water, where we had a meeting in the church (so called).
In the afternoon, paid a visit to the clergyman and his family;
he appeared a friendly man, and we had some satisfactory conversation with them.
His daughter came and spent the evening with us at our lodgings;
her mind seemed touched with a sense of Truth.
The people in this country, generally, behaved very respectfully;
those of the first rank mostly gathered about us after the meetings,
often expressing much satisfaction with them, and pressing us to go to their houses,
though I had frequently to bear public testimony against war,
as being inconsistent with Christianity; many of them are,
or have been officers in the army.
Light has measurably arisen, many are convinced in their judgments;
and I think there is ground to hope,
that the testimonies of the Truth will be exalted and held up to view,
in that settlement on Anapolis River.

Ninth Month 1st. Left Digby in a packet for St. John`'s (so called), my mind calm,
and filled with thankfulness.
Lord!
I thank you for past, and beg for future preservation.

2nd. Arrived at St. John`'s (so called); found there a schooner,
in which we sailed the same evening.
Got the Captain to land us next day at Mouse Island,
where we hired a boat to take us to Mousepecky reach.
Lodged the first night on the beach by a good fire, which we had kindled:
I slept comfortably, feeling peaceful and thankful.
Next night, we got to a little house on the shore, where some of us slept on the floor.
On the following morning,
we arrived to breakfast at the house of a person who professed with Friends;
but we could find in him nothing but talk.
We had a meeting at his house, and some of the people seemed tender.
Next morning, got a small boat to take us to Pleasant River,
where we had left our horses in going down; we found them all safe and well.

In the afternoon, we had a meeting among a very zealous people, called New Lights;
I loved and pitied them, for I think many are sincere-hearted:
but they hold some erroneous principles, and do not possess much true knowledge.
The Lord enabled me to point out the way with much clearness;
they appeared solid and attentive, and some of them tenderly affected.
Proceeded to Narragangas, where we had a meeting; from there to Stubbend,
where I had a large meeting on First day.
My mind was much exercised; but the Lord in mercy helped me,
so that I got through with satisfaction.
Left them in much love, and travelled to Wasselburgh, one hundred miles,
without having any meeting.
Attended meeting there on First day: Second day, went to Sidney: Fourth day,
took the Monthly Meeting at Vasselburgh; from there set out for New York,
attending meetings on the way at Falmouth, Portland, Salem, and Lynn.

Tenth Month 6th. Arrived at New York, where I met with my beloved friends, Martha Routh,
Mary Sevett, and Charity Cook,
who had come to this city with a view of taking a passage for Liverpool;
and feeling myself at liberty from any farther service in America,
I agreed to accompany them.
We embarked on the 17th, in the Sovereign, Captain Goodridge.

Eleventh Month 7th, 1797.
We have been three weeks at sea, and have had a pretty favourable passage so far.
Have been thrice boarded by ships of war, one English and two French;
but our Captain having all his ship`'s papers correct according to law,
they did not give us much trouble.
A Frenchman, however, examined the contents of some of the passengers`' trunks,
under pretence of searching for letters;
but his real object seemed to have been to plunder, as he carried away several articles.
On the whole, we came off pretty well; he did not get any money.

Two or three days of contrary winds have made some of our passengers sick,
though none of them are very ill.
The Lord is my shepherd; in Him do I put my trust.
I feel myself unworthy of His regard; but great is His loving kindness.

Eleventh Month 21st. Landed at Liverpool,
where I was kindly received by Robert Benson and family.--Stayed two days,
attended the week day meeting, and then proceeded directly home by coach.
Found my dear wife and family in pretty good health; and though some circumstances,
which were cause of grief and mourning,
had occurred during my absence,--yet I could do
no less than commemorate the Lord`'s goodness,
and in deep humility and thankfulness acknowledge, that I had lacked nothing.

To Ann Christy.

Liverpool, Eleventh Month 22nd, 1797.

We had a passage of five weeks, rather rough,
but not much to be complained of We had a good many passengers,
some of whom were very wild, though civil to us:
the women Friends kept pretty much to their cabins;
I was exposed alone to their disagreeable company.
I was favoured to keep quiet;
my mind composed in a sweet feeling of peace and thankfulness of heart,
in commemorating the unspeakable goodness of God, in helping through past difficulties;
and a confidence was afforded, that He continued to be our guardian.

You know I went out a poor creature;--I am returned a poor creature still:
yet through mercy, I feel love to the brethren.

+++[+++John Wigham has recorded the following:]
Have travelled in America to 20th of Seventh Month, 1796, then at Muncy, 7502 miles.
From the above date, to 6th of Third Month, 1797, at James Emlen`'s, Middletown:
2000 miles.
From ditto, to Fifth Month 24th, at Charleston: 1477 miles.
Making 10,979 miles.
Travelled in all, from my leaving home to my return, by sea and land, 22,752 miles.]
