== Chapter VI.

[.chapter-synopsis]
* Return from Ireland
* Letters
* Conclusion of His Journal
* Last Illness and Decease in 1839

Fifth Month 6th, 1813.
Returned from a visit to Friends in Ireland, Cumberland,
and some parts of Westmoreland and Lancashire, peaceful and thankful.
I set out under much fear, and a sense of weakness every way;--such bodily infirmities,
that I had little expectation of accomplishing what seemed in prospect;
but I was willing to go as far, and do as much, as I might be enabled:
and now I cannot but acknowledge,
that through adorable mercy I have been strengthened far, very far,
beyond my expectation.
May my soul forever adore and praise my gracious helper,
and acknowledge Him as the giver of every good and perfect gift!
Amen!

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Twelfth Month 11th, 1813.

The revival of trade, and the fall in the price of grain,
will indeed be a relief to many:
but alas! there appears but little of humble thankfulness among the people here;
their rejoicing is like madness, and exceedingly childish, ringing of bells,
burning of tar barrels, and dancing about the fire, like mad people,
drinking and carousing among the upper ranks, as well as the rabble.
The consideration of these things, as well as the dreadful carnage +++[+++through war]
which has occasioned these revellings, makes the heart sad.
Among the trading part of the community, much speculation is going on;
and I think much risk incurred.
Things are very uncertain, and the prudent of that class will see great need of caution;
for even when what they call fortune spreads a propitious gale,
it is wise to take some canvass in.

"`Ye are not of the world, as I am not of the world,`" said Christ to his disciples;
and they that are his disciples now, must know the separation,
and keep in the separation from the world, or they will lose their title.
Let your moderation appear unto all men.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth.
J+++.+++ Fry.

[.signed-section-context-open]
Aberdeen, Fifth Month 25th, 1817.

Shall I once more address my dearly beloved friend?
It is long since I received a scrap from your pen, and I greatly desire to hear from you.
I am aware that the care of your large family, and many other important engagements,
are sufficient reasons for your silence; but I can plead none of these things,
but barrenness and inability to write anything worth your perusal.
However, this I can say, you are as near and dear to me as ever,
in that fellowship and bond of union, which I trust,
was formed in the unchangeable Truth; and which never will decay,
except we turn away from the foundation on which it is built.
Pray for me, dear Elizabeth, that I stagger not, nor stumble,
now when I am old and grey-headed.
I am sensible that I can no more preserve myself now, than when I first set out a pilgrim.
I am still a worm.
But I have had some intimations to keep in resignation`'s harbour,
until I be sent for to pass the river; and on the other side,
I have had a prospect of a fine country:--through adorable mercy,
I think I may set up my Ebenezer and say, "`Hitherto has the Lord helped me.`"
It is in my heart to say to you, my dear friend, fear not the assaults of the enemy:
He is strong, in whom you have believed; and as you simply rely on Him,
He will cover your head in the day of battle, and teach your hands to war,
and your fingers to fight.
Conflicts of various kinds we must expect indeed,
I believe the Lord knows that these are best for us:
they have been the lot of the Lord`'s servants in every age.
We have an unwearied adversary, who not only roars about us,
but cunningly and softly whispers in order to draw us aside;
but a constant invariable application to our Captain, defeats him in all his attempts.

Let us then, dear Elizabeth, hold fast our confidence,
trust in the Lord`'s mercy and goodness,
and follow Him faithfully in the way of His requirings.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Seventh Month 21st, 1817.

I received yours, containing an affecting account of your poor Mary`'s indisposition;
we had heard of the accident, but nothing of what succeeded.
I am glad to hear she is mending, and hope she will be well before now.
It would, however, doubtless be an alarming and anxious time:
what a favour that your minds were supported under it in quiet resignation.

Affliction arises not out of the dust; and He who sees fit to permit such trials,
intends that we should profit by them; and, as John Woolman says,
that our ears should be opened to discipline,
and be favoured to see our precarious standing,
how soon and unexpectedly a termination to all things here, with respect to us,
may take place: how needful it is to be always ready.
"`Pass the time of your sojourning here in fear,`" says an apostle.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Fourth Month 15th, 1818.

I yesterday received the mournful intelligence of the removal of our dear John Robertson,
a loss that will be much felt, and particularly so by you;
your mother and I do deeply sympathize with you,
and feel our share of the general loss which the church sustains: we can, indeed,
mingle our tears with yours, and pray according to ability,
that the Lord may make up the loss;--He can do it.

I could say much of my sense of the worth of our departed friend,
but that would only tend to augment the feeling of regret, and resignation is our duty.
It is the Lord who has done it, and He never errs.
I am forbid to mourn, the dear man is released from a tribulated pilgrimage,
to enter a land of rest, in the Lord`'s time, will, and wisdom.
The great Head of the church, whose power is infinite,
can prepare and appoint officers in His house,
and qualify them for the offices to which he appoints them.
The cause is His; let us trust in Him to support it.
He can save by many or by few,
can make a little one equal to a strong nation;--He can guide,
and often does condescend to guide, his little ones,
(who have no might of their own,) as with His eye; pointing out their way for them,
and strengthening them to walk therein.
May we, dear +++______+++, ever carefully mind His motions, and follow faithfully,
though in the way of the cross.
You will need Divine direction, even in your outward concerns,
that you may not be overburdened with the cares of things pertaining to this life;
for truly, if we can get the needful accommodation for the body,
with that it is best to be content.

--

Sixth Month 29th, 1818.
I am lame and weak, but still able to get to meetings, which I esteem a favour.
Indeed I have much to be thankful for, and no cause to complain.
The infirmities of age may reasonably be expected;
but the Lord has been very good and gracious to me, far beyond my deservings.
I am often humbled and thankful in commemorating His unmerited mercy;
and if He will be pleased to preserve me, the few remaining days I have to stay,
from dishonouring Him or his cause, I shall forever praise Him.

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Fourth Month 21st, 1819.

I send along with this, William Penn`'s Key, for +++_____+++'`s perusal;
it is an old book but contains what we believe in doctrinals, in little compass;
in reading which he may see, that a belief in Christ,
by a measure of His Spirit manifested in our hearts, as a reprover, instructor, leader,
and comforter, was from the beginning and still is our principle.
This is what our predecessors +++[+++in religious profession]
found and were convinced of, were settled and centred in,
and they found it to be light and life:
and so far was it from leading them to disesteem the great propitiatory sacrifice,
that it gave them clearer and more satisfactory views of its efficacy,
than they ever could attain by all their researches,
till they embraced this precious principle of light and life.
By it the scriptures were opened to their understandings,
and the mystery of redemption unfolded to their view:
and this principle is our principle still,
notwithstanding the many weaknesses that appear among us for lack of attention to it.
If J. M. does not believe herein, he is not of us:
and perhaps he had better join himself to that society,
with whose views he can more unite.
But I love him, and feel for him;
and I much wish that he would turn his mind more inward,
and have less dependence on his own understanding,
also in simplicity receive the engrafted word, and walk in the light of it;
and then he would come to have fellowship with Christ and with his servants,
then would he indeed know the blood of Christ to cleanse him from all sin.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Sixth Month 24th, 1819.

Your account of the Yearly Meeting was pleasant and reviving;
and so many Friends remembering us poor old worn out bodies, was and is grateful;
and raises a hope, that unworthy as we are, the Lord has not cast us out of remembrance:
even your description of your own stripped and poor state of mind,
is to me not discouraging.
I have often experienced dispensations of this kind,
and even now my state is very similar--a mind tossed and perplexed,
because I cannot get it stayed and centred where I would willingly have it to be,
on the one great object:
but former experience of the gracious goodness and long suffering of my dear Lord,
makes me hope, and try to adopt the language of the Psalmist, "`Why are you cast down,
O! my soul, and why are you disquieted within me; hope in God,
for I shall yet praise Him, who is the health of my countenance and my God.`"
The ways of God are incomprehensible; indeed I sometimes think,
that man (the workmanship of His holy hands) is an incomprehensible creature;
and the mystery of godliness--the mystery of redemption,
is great and deep;--and the dispensations that the all-wise God sees
fit to make use of for its accomplishment are wonderful,
and often at the time they are operating upon us we cannot comprehend their usefulness:
yet as they are patiently abode under, in a humble trust in Him,
who alone can carry on the work,
they do not fail to accomplish that for which they are intended.
To humble us and keep us humble, requires Almighty power; such is our fallen nature,
and self in its workings so subtle, that it needs a great deal to subdue it thoroughly.
I have felt it so with respect to myself:
and I fully believe many humiliating conflicts are absolutely needful for us,
but perhaps not to all alike; I may need more of these than some others:
the desire of my heart is, that the Lord may not spare,
till He has made me just what He would have me to be.

"`Trust in the Lord with all your heart,
and lean not to your own understanding;`" and there is no doubt with me,
but all will be well.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Twelfth Month 23rd, 1820.

It is certainly safest to be in a little way +++[+++of business]
these times: may the Lord be your counsellor,
and give you contentment with food and raiment,
and enable to live so loose from the world,
that you may be ready to answer his requirings in all things,
during your stay in this your pilgrimage.
I feel much satisfaction in having given the Lord`'s work the preference,
and laboured in my small measure while I had strength; for verily we have but a day:
now when I am useless, (and indeed I was always a poor creature),
He has given me a hope in his mercy,
which is as an anchor--a comfortable anchor to my poor mind,
for which I hope I am thankful;
and if He preserve me to the end from dishonouring His cause, I shall praise Him forever.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Eleventh Month 24th, 1821.

I would have acknowledged your letter sooner,
but I have had such a rheumatic attack in my head, as to unfit me for writing,
and even now I am unfit.

I dwell in a weary land, but I have the shadow of a mighty Rock;
and though the Lord sees fit to keep me poor, He grants me a hope in His mercy,
which is an anchor to my poor mind; and when I get one trying day over,
I console myself with thinking, I am another day nearer the close.

I do not wonder at your feeling frequently low and depressed;
it is the path that all the faithful followers of a crucified Saviour have to walk in.
He is described in Scripture as a man of sorrows and acquainted with grief;
and surely it is enough for the disciple to be as his Lord.
Let us in these low seasons still trust in Him: He knows what is best for us,
and He feeds his children with the food convenient for them; He puts forth his sheep,
and goes before them:--mind, dear +++______+++, His putting forth,
and follow Him in the way of his leadings.
When you were a child, I was a man; and now I am the child, and you are the man.
A word to the wise is sufficient.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Niece, Margaret Wigham, late Johnston.

[.offset]
+++[+++It is without date,
but supposed to have been written about the time of her leaving Aberdeen.]

I shall miss you much; but hoping you are going to your right place, I am resigned.
May you and your dear Thomas grow in grace, become established as pillars in the church,
and be made instrumental in building up that little meeting,
where you are gone to reside.
Cross occurrences, trials and conflicts, you must expect,
or else your lot will not be like that of other pilgrims;
but whatever the trials of your day may be,
be sure to keep this point in view--the honour of God;
prefer Him and His cause to every other thing; never mind self,
let that be of no reputation:
still strive to learn of the Divine Master to be meek and lowly in heart;
then you will undoubtedly experience all things to work together for good.

I need not say much; you have the unction from the Holy One,
that will teach you all things needful for you to know, as you carefully attend to it.
I love you as a daughter, and shall always be pleased to hear from you.

First Month 16th, 1821.
You are a little company in Corwood Meeting, which I frequently think of,
with desires that you may be built up together in the Truth,
and stand as ensigns to the people about you, that your lights may shine, which,
if you are circumspect and watchful, will be the case.
The Lord will do you good.

--

[.offset]
+++[+++To His Nephew, Thomas Wigham, written soon after the decease of his wife.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
First Month 18th, 1823.

I nearly sympathise with you in your recent great loss, also with your dear mother;
she will feel much; it will greatly increase her concern for the poor children:
but resignation must be sought for.
Young, when writing on the subject, says:--

[verse]
____
What cannot Resignation do?
It wonders can perform:
That powerful charm, "`Your will be done,`"
Can lay the loudest storm.
____

We too have had a heavy loss in the removal of our dearly beloved
Elizabeth Glenny--+++[+++a granddaughter who resided with him.]
But I have remembered what Christ said to his disciples, "`If you loved me,
you would rejoice, because I said, I go to the Father.`"
When we have a well grounded hope,
that our near and dear friends are centred where there is no more pain nor sorrow,
and consider the many snares that await us in this pilgrimage;
we may rejoice in the belief, that they are forever safe.

My love to A. H., and tell her, if she do her duty,
she will take good care of the motherless children.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, First Month 29th, 1823.

Young and old are liable to many ailments,
and are removed at all stages of their existence; and as you have well observed,
the consideration thereof calls upon us to endeavour to be ready.
I never felt more need of watchfulness and circumspection,
nor a greater sense of weakness and inability to
preserve myself--more need of Divine aid,
than now, when I am grown old; so that if the Lord help me not,
I shall yet become a castaway, notwithstanding all my former preaching to others:
but thanks be to the Lord for the hope I have in his mercy.

We do feel a great loss in our dear Elizabeth Glenny; but how can I mourn?
I loved her dearly,
and being satisfied that she is happy--removed from all
the snares that await us in this pilgrimage,
how can I mourn?--when I hope she, whom I so dearly loved, is rejoicing,
and singing hallelujah to the Lord God and the Lamb.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Second Month 5th, 1824.

As to my spiritual attainments, I am as weak as a child;
only through mercy I still retain a confidence in the wisdom, power,
and goodness of my dear merciful Lord; and endeavour to rest contented in His will.
The removal of Margaret Wigham, now in the middle stage of life,
has a warning voice in it.
It is cause of rejoicing to hear that the Lord is preparing
and anointing some of the youth to advocate His cause.
I hope, dear +++______+++, if he step cautiously and in fear, and yet faithfully and honestly,
that he will grow in the root, and bring forth fruit answerable to that growth.
With respect to the depression and discouragement which it is your lot at times to feel,
it is nothing new, and only what all the Lord`'s servants at times experience;
and especially such as are His messengers to the people.
The great and eminent Apostle Paul had his share; pressed above measure,
despairing even of life, had the sentence of death in himself: but what was this for?
that he might not trust in himself, but in Him who could raise the dead.
He also speaks of filling up our measure of what
remains of the sufferings of Christ for the body`'s sake,
which is his church: now I understand this to mean, that those who are united to Christ,
feel the oppressed state of the seed in the hearts of the people,
through the prevalence of wrong things; and this depression may often be felt,
when no way opens for relief--no, even when we do not see the cause of it.
Patience is then necessary, to wait the Lord`'s time for a change of the dispensation.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Eleventh Month 21st, 1827.

I often think of you at +++_____+++, with fervent desires that you may be preserved,
and grow in every good experience--grow downwards--grow in humility and love,
be more and more reduced to nothingness of self.
We are never in that perfect state, unto which we are called,
till all self-esteem is battered down;
there is such a propensity in human nature to wish to be esteemed somebody.
O! what a hammering this propensity takes to reduce it to dust;
and until this is effected, we cannot so fully esteem others better than ourselves,
and bear one another`'s burdens.
May you be made, just what the Lord would have you to be,
true standard bearers and ensamples to the flock.
I often feel a near sympathy with you in particular,
believing you have many heavy burdens to bear; but the Lord is your shepherd,
you shall not lack strength to support in every exercise.
Trust in Him with all your heart, and lean not to your own understanding.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Third Month 5th, 1828.

I have frequently thought of writing you, since I received your last acceptable letter;
but it is a task now to set about writing.
I am not sorry that you see and feel the stubborn stuff of which your heart is made
(as you express it;) nor that you should experience low and doubting times.
These mark the path, I apprehend, of most, if not all, who travel from Babel to Bethel;
at least with respect to myself, +++[+++I can say]
it is a state I have often been in, even at the very brink of the pit of despair;
but yet the Lord in His mercy has plucked me back from plunging therein,
and given me renewed hope; and if I am saved at last,
(which I now hope I shall be,) I must acknowledge that
it is altogether of the Lord`'s mercies,
and to Him belongs all the praise.

I have seen the profitableness of these proving dispensations;
they tend to reduce into a state of self nothingness and humility,
which is the grand point, the best and safest state we can be in.
Infinite wisdom knows how to bring us to this state; He knows our nature,
and the plunges we need to reduce us, and bring us into it;
you need not be too much cast down in the process, but trust in the Lord,
and be watchful, and He will bring it to pass.
There are indeed many temptations and snares, so that we have great need of watchfulness;
yes frequently begging of the Lord to help us to watch,
for we are poor watchers without His help.

--

+++[+++The following is stated to be the last letter he wrote, and may come in here,
though of later date than the next and concluding paragraph of his journal.]

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, Second Month 20th, 1829.

The expression of your sympathy, and the hope you have for me, is truly grateful;
and I may say through unmerited mercy, I am favoured with a hope for myself,
that when this weary pilgrimage is over,
I shall be admitted into one of the many mansions in our heavenly Father`'s house,
where the inhabitants of even the lowest are completely happy.
I am a poor thing, not worthy of the least of the many mercies bestowed upon me;
but I think I can say in truth, I love the Lord, and his people,
and often feel solicitous for the preservation of the few Friends at +++______+++.

I cannot write much, the little I have now written,
has obliged me to stop and rest my eye, before I could see where to make a stroke;
I must therefore conclude with the expression of a saying of our blessed Lord,
"`Blessed are the peace makers, for they shall be called the children of God.`"

--

[.offset]
+++[+++Final Journal Entry]

Ninth Month 17th, 1828.
I am now in my eightieth year, a long and weary pilgrimage: many conflicts,
many trying exercises, have attended me; yet through all, the Lord has sustained me.
It seems as if I had well nigh finished my course; I say not I have kept the faith;
but the Lord has kept me in the faith: and I feel near and dear to me His precious cause,
which I believe He engaged me to advocate;
and though day after day passes over in much weariness of the flesh,
yet by His sustaining love, the bitter is sometimes made sweet,
and what would otherwise seem hard, is made easy.
I feel constrained to say, that the Lord is good, inexpressibly good:
and I have an unshaken hope, which is the precious gift of God,
that when the conflicts of time are over, I shall enter a region of everlasting rest,
peace, and joy.
I leave this as my testimony to the goodness of God,
(probably the last memorandum I shall make in writing),
that my children may see and believe,
and be encouraged to follow Him in the way of His leadings;
that in the end they may have to rejoice in the Lord,
and joy in the God of their salvation, as does my soul this day.
I sensibly feel I have no merit;
I am unworthy of the least of the mercies bestowed upon me; the love, grace,
and mercy of God through Christ Jesus, has done all for me.

I do most firmly believe in the divinity of Christ; that God was in Christ,
reconciling the world unto himself:--that the
Scriptures were written by inspiration of God,
and they give abundant evidence of the miraculous conception, birth, life,
and death of Christ,
and their testimony is corroborated by the internal evidence vouchsafed to believers,
displaying the glorious mystery, which angels desire to look into.
Finite wisdom cannot indeed comprehend the deep things of God;
but the wisdom from above opens, to those who seek it, what is necessary for man to know;
and man ought to be content with what the Lord is pleased to reveal,
and not strive to comprehend by the earthly wisdom, things incomprehensible.
True believers, whose minds are mercifully opened,
feel the efficacy of Christ`'s death in salvation from their sins.
Thus much I think right to remark,
respecting my belief in the divinity of Christ and the truth of the Holy Scriptures.
Through this faith my dear wife obtained the victory,
and was enabled to triumph over death, hell, and the grave;
as evinced by almost her last expressions, praising the Lord with her latest breath.
I feel the loss of her company; but do not regret that she is gone before me,
(as I trust) "`to be with Christ, which is far better.`"
She has left me to struggle a while longer with bodily infirmities and weaknesses,
which she indeed felt largely in her own experience.
A true sympathizer was she.
I have kind and affectionate children and grand-children,
who do all they can to make me comfortable;
but younger people cannot enter into the feelings and infirmities of age.
O Lord! keep and preserve me to the end.
Amen, and Amen!

[.asterism]
'''

The preceding effusion of pious feeling written by my honoured father, as he states,
in his eightieth year, proved as he had anticipated,
with the exception of a letter to one of his sons, the last production of his pen:
but as he lived for upwards of ten years afterwards, it may perhaps be allowable,
and not inappropriate for one, who during several of the latter years of his life,
was privileged with being much in his company,
to record some particulars respecting him during that period.
This is not done with any view of exalting the creature, or eulogising the dead;
but by exhibiting the character,
and final close of a dedicated and humble disciple of our holy Redeemer,
to magnify the efficacy of that Divine grace, which had sustained him all his life long,
and by which, he was ever ready to acknowledge, he was what he was;
and also to prove an incitement to such of us as are still pilgrims on this earth,
to be using all diligence to make our calling and election sure,
following on in the same precious faith by which he obtained the victory;
that being "`washed, sanctified, and justified, in the name of the Lord Jesus,
and by the Spirit of our God,`" we may, when the day of our probation is over,
know an entrance ministered to us abundantly into His everlasting kingdom.

At the time when my dear father wrote what concludes his own account,
(1828,) his eye-sight had become very defective, and soon afterwards it totally failed,
so that writing became impracticable.
His lameness also was such, that with difficulty he could move about,
requiring even a painful exertion, to get occasionally into his garden;
but during the long period of his confinement to the house, he was,
under all his privations, and the pressure of many painful ailments,
full of a contented resignation,
often saying he had much cause for gratitude and thankfulness,
for the many blessings and favours he still enjoyed.
He was usually very open and cheerful,
which rendered his company attractive to his friends,
and he seemed to enjoy their visits;
and while at times he felt at liberty to converse pleasantly with them,
on passing events, yet it was evident to a serious observer,
that his mind was centred on eternal things,
that "`his heart was fixed trusting in the Lord.`"

His love to his friends, he used to say, was not lessened by increasing years.
His attachment to the precious cause of Truth remained as strong as ever;
and to such as visited him, whether those of his own meeting or from a distance,
he was sometimes engaged to drop a word in season, mostly short,
but weighty and instructive,--like the well-instructed scribe,
"`bringing forth out of his treasure things new and old;`" and on these occasions,
even when no communication of a religious character took place, many, it is believed,
can acknowledge, that there was a sweetness and solemnity to be felt,
under which they have been edified and comforted;
so that they could have adopted the language, "`it is good for us to be here.`"

For a number of years he seemed to live in a state of constant waiting for
the call of his Divine Master to put off his earthly tabernacle,
that he might be "`clothed upon with his house from heaven;`" feeling himself,
in his own estimation, so deprived of usefulness,
that he said he was sometimes ready to wonder, why his stay here was so much prolonged;
but would add something to this import, "`the Lord, who knows all things,
knows what is best for me; when He sees fit in His unerring wisdom,
and when his own purposes are effected,
He will release me from rather a trying and painful getting on.
I desire to be wholly resigned to do or to suffer His will.`"

He sometimes said, he was tried with low times,
and that the enemy was even permitted to buffet him;
yet through all he was favoured with a hope, which never forsook him,
that when the end came,
all would be well,--that one of the many mansions in
his heavenly Father`'s house would be allotted him:
adding, that he thought there might be a difference in these mansions,
even as one star differs from another star in glory;
but no doubt there was happiness without alloy in all of them.

For several years the meetings of ministers and elders were held at his house,
which he said, he considered a privilege,
being the only meetings he had the opportunity of attending; on one of these occasions,
in allusion to the trials that had arisen in our religious Society,
he expressed himself to this effect: "`although I often feel like a worn out instrument,
laid aside as useless,
nevertheless earnest desires are frequently raised in my mind for the prosperity of Zion;
and notwithstanding the many causes of discouragement that prevail amongst us,
I am permitted to believe that the Lord will not suffer His blessed
Truth to be trampled under foot:--He is still with his people,
and as they keep humble and low, He will continue to be with them.
The shout of a King is yet in our camp; therefore let us not be dismayed,
but thank God and take courage.`"

At another of these meetings, being the last but one at which he was present,
he made a communication of the following import:--"`As this is
probably the last time I shall sit with you in this capacity,
I feel free to tell you, that all is well.
I have not been following cunningly devised fables;
neither have I been endeavouring to serve the Lord for nought:
notwithstanding my unworthiness, my many weaknesses, and short comings,
He has richly rewarded me.
And I may tell you, that if you continue to persevere in faith and patience,
in stability of conduct,
He will crown your latter end with loving-kindness and tender mercies,
as He is abundantly doing for me.`"

In the early part of 1837, he took cold, and had a cough that distressed him much,
especially during the night; at this period, on one of his sons taking leave of him,
and a daughter-in-law, expressing a hope that he might have a better night, he replied,
he had no hope of that kind:--"`My hope is in my God,
that he will forgive my sins,--or rather +++[+++my belief is]
that He has forgiven them; and I feel thankful to Him for that.`"

About a week afterwards, he expressed himself thus:-- "`My cough is rather better;
and were it not that I feel often so sickly, and my relish for food so much declining,
I might perhaps get better of this cold, as I have of many other colds;
but these feelings preclude that expectation, not that I know anything about it, for,
+++[+++respecting the issue of the present illness,] I know nothing; but this I know,
that it is my duty to wait patiently the Lord`'s time, which we are sure is the best time.
It looks pleasanter to be dissolved, and freed from suffering;
but then I desire to be content and resigned to His will.`"

He recruited soon after this time, and continued,
though under an increase of bodily ailments,
in his usual state of cheerfulness and mental energy, till the beginning of 1839;
when from his declining state, it became evident to his relations and friends,
as well as to himself,
that his continuing much longer in mutability was not to be expected.

In concluding this little tribute to the memory of my revered parent,
I think I cannot do better than introduce the
substance of some part of his own expressions,
that were noted down or remembered, during what proved his last illness.

On Third day morning, the 26th of Third Month,
speaking of his having passed a more comfortable night
than any he had done for a long time before,
in much tenderness of spirit he expressed how thankful he felt for the favour,
to his Lord and Saviour, adding,
"`If I had taken the medicine they were urging me so much to take,
it would have been said that it had done it;
but as the relief has come without any outward means,
I esteem it a direct interference of the Lord`'s hand:
He has seen fit to give me a season of ease from great pain.`"

Seventh day, 30th. On being inquired of how he was, he replied,
"`I am just about as weak and poorly as I can well be;`' but added,
"`I have a hope--I am favoured with a lively hope, that when I have done with time,
I shall have peace forever:`' and on its being remarked that
it was a great mercy to have such a feeling to sustain him,
he said, "`O yes! and none can tell how precious it is, but those who feel it.`"

Fourth Month 4th. This morning, suffering intense pain in his foot and leg, he said,
"`I find it no easy thing to arrive at entire
resignation to the Lord`'s will under this pain,
though I do sincerely desire it.
I cannot always suppress desires arising for relief in my own way;
but if patience only holds out to the end, I will try to struggle on.`"

In the evening of the same day, he was seized with a fit of severe pain and sickness;
and thinking his end near, he sent for some of his family who were not then with him:
on one of them asking him how he felt, he replied,
"`I seem to be wading through the Black river, over which Bunyan says there is no bridge,
and so deep, that poor Christian could scarcely keep his head above water;`' adding,
"`I have no desire to get better, but just to be wholly resigned to His will.`"
The agonizing pain he was suffering seemed so to overpower him,
that he appeared unable to proceed; at length, after a pause,
addressing himself to his children, he said,
"`you too must follow on;--never let go your hold;--
keep to the Rock that never failed anyone.`"

Fourth Month 7th. Since the preceding date,
there was little or no abatement of his sufferings, and he obtained scarcely any sleep,
but he was enabled to bear them with great patience.
On one of his family, who was taking leave of him for the night,
asking him if he had anything to communicate, he answered, "`pray for me,
if you can,--that I may be released if it be the Lord`'s will.`"

The same evening on a message from a son, residing at a distance,
being communicated to him,
in which allusion was made to the crown immortal being in prospect,
and the assurance of its being bestowed on him before long,
with that diffidence and humility, which peculiarly marked his character,
he replied,--"`there is a hope to be sure, that sustains.`"
He then mentioned, that a Friend who had visited him some years before,
had told him of a certain high professor,
who had stated that he never met with a Quaker who had true faith, they had no assurance.
"`Hope`" or "`trust`" was all any of them could say.
"`But,`" added my father,
"`that Friend and I thought we could be content with a humble hope.`"
In confirmation of this view, allusion was made, in conversation with one of his family,
to an expression of Samuel Emlen at a time when
he was sick in London;--"`Thanks be to the Lord,
for the hope I have in His mercy;`" on which Joseph Gurney Bevan makes the
following striking remarks:--'`It then seemed,`" (says he) "`a less strong
expression,
than probably through inexperience I then should have expected,
from a man whose whole life seemed devoted to God.
I have since lived to see,
that it contained everything which the self-abased Christian can desire;
and such a Christian was he.`"
(See Piety Promoted, Tenth part, p. 126, second edition.) At another time he remarked,
that some had triumphant deaths; but this was the experience of comparatively but a few,
and was, he believed, not necessary.
One of the lowest of the many mansions was all he desired,
and there seemed no cloud to intervene.

About a week before his final close, being visited by a son from a distance,
after speaking of his great weakness and continued suffering,
he expressed himself to this effect,
"`It is a great support--an inexpressible satisfaction,
the prospect of peace and rest when the struggle is over.
Nothing to trust to, but the mercy and goodness of the Almighty,
and being engaged in seeking for resignation to His holy will.
Perhaps this is the most acceptable state we can attain to,
the pain and suffering is nothing new, it is the way of all living.`"

During the last two days of his life, he seemed much sunk in exhaustion,
and desired quietude, expressing but little,
and the power of articulation being impaired, he could not well be understood;
yet with little exception he appeared sensible, and patiently waiting his appointed time.
He was heard repeatedly to utter: "`I want rest,--I want to be at rest.`"

In the morning of the 17th of Fourth Month, 1839,
he was peacefully released from the shackles of mortality.
His surviving relatives can humbly rejoice in the full belief,
that through redeeming love and mercy, on which his hope was placed,
his purified spirit has entered into the joy of his Lord.
He was aged upwards of ninety, and had been a minister about sixty-seven years.
His remains were interred in the burial-ground belonging to
Friends at Kinmuck on the 20th of the same month.
