== Preface

John Wigham, the author of the following pages,
was the son of William and Rachel Wigham of Hargill House in Cornwood,
in the county of Northumberland; and the grandson of Cuthbert Wigham of Burn House,
in the same township.

Respecting his grandfather there is a short
account in the second volume of Piety Promoted,
by John Field, at page 462,
from which the following is extracted:--'`He was
educated in the way of the Church of England;
and was in his youth addicted to many youthful follies, and some gross evils.
But it pleased God, who is rich in mercy toward sinners to call him by His grace,
and to reveal His Son in him; whereby about the year 1734,
he was convinced of the blessed Truth as it is in Jesus, and received it.
Being thus brought into deep judgment for his transgressions,
and sensibly feeling God`'s wrath poured forth,
he durst no longer follow his old courses and ways of living,
nor durst longer associate with his old companions;
but joined in Society with the people called Quakers:
and several of his neighbours being about the same time convinced of the Truth,
he was made instrumental in settling a meeting at Cornwood, in the year 1735.
About a year after his convincement, a dispensation of the gospel was committed to him;
in which he laboured faithfully, according to the ability given.
His ministry was not with the enticing words of man`'s wisdom,
but in the power and demonstration of the Spirit.
He often had to magnify that power,
which had redeemed his soul out of the horrible pit of everlasting darkness;
and having known (as he expressed it) the terrors of the Lord for evil doing,
he was earnestly engaged to warn others to take heed to their ways,
lest they should bring themselves under such terrors as he had felt;
but from which he now, through infinite mercy, was released;
and was come to the enjoyment of that peace, which the world cannot give or take away.`"
He died in 1780, aged about seventy-seven years.

The author`'s mother, Rachel Wigham, whose maiden name was Teasdale, was also a minister;
and must, it is presumed,
have been pretty well known in that character from her extensive gospel labours.
The testimony respecting her, issued by Allendale Monthly Meeting, states,
that about the twenty-fourth year of her age,
she was joined in marriage with William Wigham of Hargill House in Cornwood;
and very soon after she came forth in public testimony in meetings,
which was very acceptable to Friends:
and by carefully occupying with the talent received,
she became an able minister of the gospel.
Her service in this capacity was very great in the meeting to which she belonged;
and she was several times drawn forth in gospel love,
to visit the meetings of Friends in divers counties of England and Wales,
and also in Scotland and Ireland: in all which services,
we believe her labours of love tended to the edification of Friends and her own peace.
She finished her course at the house of her son-in-law at Allendale,
the 6th of Fourth Month, 1813.

In preparing the succeeding Memoir for publication,
which the writer appears to have penned especially for the
benefit of his own descendants and surviving relatives,
it has been deemed needful to make some omissions and abridgements;
and occasionally for the sake of greater perspicuity,
an alteration or transposition of some of the sentences has been introduced;
but in no case has there been any intentional deviation from the meaning of the Author.

A few explanatory notes, and some concluding remarks have been added by the Editor;
who may be permitted in this place to express regret
that the preparation of the present work for the press,
has not fallen into hands more competent for the task,
being sensible of his own deficiencies, in many respects, for the undertaking:
but seeing the duty has devolved upon himself, he has been willing to do his best,
trusting to the candour and indulgence of the reader,
to excuse and pass over the faults and errors that may meet his eye.

In presenting to the Society of Friends and the public in a printed form,
what appears to have been written more particularly for private perusal,
some apology may appear requisite.
The reasons for adopting this course may be stated very shortly, The Editor,
and other relatives and friends of the deceased Author, believing, as they do,
that there is much valuable instruction contained in what is thus offered,
think they should have been doing wrong to withhold it; and, moreover,
they can hardly entertain a doubt, but that it will prove acceptable to many.
It is true, that most of the Author`'s contemporaries have passed away before him;
but there are still remaining not a few who knew his worth,
and cherish love and respect for his memory: some survive, it is believed,
who have been witnesses of his abundant and devoted gospel labours;--others, it may be,
on whose hearts he has left seals of his ministry;
and these would doubtless regret being deprived of the edification they may derive,
from even an imperfect sketch of his religious exercises and experience.
The Editor also entertains a hope, that the rising youth in our religious Society,
may reap instruction and benefit in the best sense from the example of dedication,
thus exhibited in the life of a humble,
self-denying follower of our holy Redeemer;--that they may see, to their comfort,
that "`Godliness is profitable to all things, having promise of the life that now is,
and of that which is to come.`"

With these views and impressions the publication is put forth,
and with earnest desires that the perusal of it may be blessed to the reader;
that it may be the means of quickening and stirring him up afresh,
by putting him in remembrance of the things already known,
and encouraging him to become more decidedly a "`follower of them,
who through faith and patience inherit the promises.`"

Anthony Wigham

Aberdeen,

Twelfth Month, 1841
