== Chapter I.

[.chapter-synopsis]
* His Birth and Parentage
* Religious Exercises in Early Life
* His Marriage and Call to the Ministry
* Removal into Scotland

As I have frequently had it on my mind,
to leave behind me some record of the Lord`'s gracious dealings with me from my childhood,
for the information and encouragement of my offspring;
and being at this time renewedly impressed with the uncertainty of my time in this world,
I feel afraid to delay it longer.

To begin now, this 5th day of the Ninth Month, 1808, in the 60th year of my age.
I was born at Cornwood, near Haltwhistle, in the county of Northumberland,
the 23rd of the Third Month, 1749, and was blessed with religious parents.
My mother particularly, was deeply concerned,
that her children might be carefully educated in the way of truth,
and preserved from the snares of the world; and with this view,
she often exhorted us to be attentive to the guidance of the
Holy Spirit secretly manifested in our own hearts;
which was of great benefit to me in my childhood: for,
as the Lord was graciously pleased sensibly to visit me when very young,
I was made aware,
sooner perhaps than many children who are not favoured with such instruction,
what that Spirit was, which both reproved and comforted me.

When I was about eight years of age,
strong desires to be the Lord`'s servant were raised in my mind;
and being made sensible that I could not serve Him acceptably,
unless I were preserved from evil, I often begged in my childish way,
that He would enable me to overcome all my evil propensities, which I saw were many:
and although I frequently entered into covenant with my God to be watchful,
especially when under His correction, yet I felt great weakness,
and frequently committed errors.
I was naturally lively and wild, and of a hasty passionate temper;
which often hurried me into things for which I felt condemnation, and which,
in my more serious moments I detested; knowing them to be evil,
and sensibly feeling that they separated me from Him, whom my soul loved.
For the Lord was sometimes graciously pleased so to fill my heart with his love,
that my soul was quite enamoured; and under that influence,
I thought I could cheerfully suffer even death for His sake.
But when his face was veiled, and I was under his correction for evil,
then the enemy of my happiness, by his insinuations,
endeavoured to persuade me that I might as well give over striving, and live at ease;
for I should never be able to overcome my evil propensities.
For some time, I was in great horror of mind on these occasions, and nigh unto despair:
when the Lord would again comfort my tossed mind,
frequently by bringing to my remembrance some of His gracious promises,
and enabling me to take fresh courage and renew my covenant.
Thus were spent my childish days and years.

I do not know that any one perceived that I was under any +++[+++religious]
exercise whatever, for I took great pains to conceal it,
being afraid that any of my companions should know it:
for though the Lord was thus graciously dealing with me, and though,
when my heart was filled with love, I thought I could suffer anything for Him;
yet I was far from having attained to a willingness to confess Him before men.
When a boy, I was frequently employed in taking care of sheep, all alone;
and when so situated, my mind was often drawn to seek the Lord; and to my exceeding joy,
He was sometimes graciously pleased to be found of me;
and my heart was melted within me;--love inexpressible flowed towards God and man.
In these seasons He began to discover to me,
that if I would be his servant and retain his favour,
I must tell to others what He had done for me; and I still believe,
that had I happily kept close to Him and been faithful,
I should have had a testimony to bear for His cause, when very young in years: but this,
alas! was not the case; for as I grew older, my father, who was a very industrious man,
put me to work with the servants, whose company proved very pernicious to me.
My father, whose memory I revere, had a care for his children`'s preservation;
but was not I think sufficiently aware of the danger to which we were exposed.
From the time I was about sixteen years of age, I rapidly lost ground in religion:
for I began to delight in company, which proved a snare to me;
and I was led into many wrong things, and gradually lost that sense and savour of Truth,
with which I had before been favoured; so that my mind became darkened,
and I even called in question all those feelings I had experienced at an earlier period:
thus indeed was experienced the force of the remark,--
"`a little leaven leaveneth the whole lump.`"
The reasoner too got entrance,
and I grew wise to dispute against and strong to stifle conviction.
Yet the Lord in mercy followed me long with his reproofs, and made me feel,
even in the time of my rebellion, much bitterness of soul.
Oh, I have often remembered the bitter wages of the cunning adversary;
for though he could promise pleasure,
he could not give peace.--I was ensnared by evil company.

I leave this as a warning to others to beware of evil company;
and to those of my offspring, who are, or may be parents,
let them never if they can possibly avoid it,
expose their children to this dangerous temptation.
In my worst state I was, through great mercy,
preserved from what the world calls gross sins: but alas!
I left my God, my guide, and bitter suffering was the consequence: and, had He left me,
I had been undone forever.
But He mercifully followed me with His judgments:--I had no
peace;--merry nights were succeeded by sad mornings.
I often bewailed my condition, and longed to be freed from my fetters;
but I had no power or resolution to break off from my companions:
though sometimes when the Lord`'s judgments were heavy upon me, I resolved to do so;
but having departed from Him, in whom alone is the power, He, in his justice,
left me enslaved in bitter servitude.
Thus I spent several years in a state of rebellion against my God: at length,
in His mercy, He made a way for my deliverance.

My father having suggested my entering into the married state,
I went to see a young woman, to whom I became affectionately attached;
and having obtained her consent,
we were united in marriage before I was quite twenty-one years of age.
This union proved a great blessing to me at the time,
and my beloved partner has been a blessing and a helpmate to this day; for though,
like myself, she had not then much religion, yet by this step I became settled,
and was rescued from those associates, who had so much injured me;
and it was not long before the Lord was pleased to visit us both afresh.
Weary of my servitude to sin, I was thankful to embrace liberty on any terms,
and would gladly have returned to the right way;
but many of the corrupt inclinations of my nature, which, through grace,
had been somewhat subdued in my childhood,
were now by my revolt and disobedience much strengthened, and a great conflict ensued.
I was made sensible that I had no power of myself to obtain the victory,
that the power was in and of God alone, dispensed through his grace or good Spirit.
Thus, I was exceedingly humbled by the sight I had obtained of my condition;
I felt such a load of guilt upon me, and such propensities to add thereto,
that I was often very near to despair.
For though the Lord was graciously pleased to open to my view the fountain,
the blood of Christ, to cleanse from all pollution; yet I saw, at the same time,
that that fountain was opened only to those,
who repent and forsake all those things that defile:
and though I believed my repentance was sincere,
as I did from my heart abhor myself and all my former sins,
yet I felt so much weakness and such strong desires and temptations
to some things which I knew to be displeasing to the Almighty,
that I was for some time almost without hope.
All my grievous struggles were however in secret; none knew them but the Lord alone:
for I was afraid to let it be seen that I was at all exercised about religion,
lest I should fall, and dishonour the cause,
and prove a stumbling-block in the way of others.

Whilst I was thus labouring under these exercises of mind, the Lord showed me,
that though man could not help himself, he could injure himself;
and thus was brought to my remembrance this language, "`Thy destruction is of thyself;
but thy help is in me.`"
I was convinced that God was willing to save all men;
and for that end He visited them by His grace,
inviting them to accept and use the means He offered them, namely,
a measure of His light and grace;
in which he dispensed power sufficient to give them the
victory over all their spiritual enemies,
if they would embrace it, and become co-workers with it.
But if, on the other hand, they neglected to lay hold of and use the means,
the fault was their own, and their destruction of themselves.
Thus I saw, I must maintain a warfare, and resist and strive against temptations,
in watchfulness and humble dependence on the Lord`'s strength.
The way being thus clearly opened before me,
I was made willing to enlist under the banner of Christ,
and prayed that He would enable me to be a faithful soldier: but, alas!
I was often surprised and wounded, when off my guard;
and I should have fainted had not my gracious Redeemer manifested
himself to be a High Priest touched with a feeling of my infirmities.
I now began experimentally to know Him in his various offices;--passages of
scripture were often brought to my remembrance for my refreshment,
and for the strengthening of my faith.
I recollected the testimony of the Apostle, that we have an advocate with the Father,
and that for his sake God was propitiated.
I felt that He refreshed and strengthened me, as well as washed and healed my wounds,
by his balsamic virtue.
Oh!
I often to this day remember his unutterable goodness to my exercised mind.
He had won my heart;--He knew my sincerity: and though,
through unwatchfulness and infirmity, I often failed on my part;
yet in His mercy He did not leave me.

Having, about this time, entered into close covenant with my God,
I felt very desirous of having a sound faith;
and began to be exercised about some points of Christian doctrine.
The state of children dying in infancy, occasioned me considerable perplexity;
for though I could clearly comprehend that Adam our first parent,
by transgressing the Divine command fell, so all his offspring were in a fallen state,
and though I was satisfied with respect to the means provided
for their restoration through Christ the one offering,
and by the operation of the Holy Spirit in the heart subduing the corrupt nature,
and by the washing of regeneration, making new the creature,
yet I could not conceive how infants could experience this change;
and to suppose that such were excluded from God`'s kingdom,
appeared contrary to the declaration of Christ--"`of such is the kingdom of heaven.`"
I knew there was an invention among men, as a kind of salvo for this difficulty,
that of sprinkling, or what they call baptism;
by which they profess to believe that the child is
regenerated and initiated into the church of Christ:
but this appeared a fiction, and not at all satisfactory to my mind.
I tried to come at a right knowledge of the subject by
an examination of other men`'s opinions,
and by comparing these with Scripture testimony, but without attaining what I desired.
At length, the Lord condescended so to enlighten my understanding,
that I was left without doubt.
I well remember the very time and place when the matter was opened to me,
and in a way that satisfied me at once, and has done so ever since: it was thus,
that as Adam`'s sin was disobedience, and aspiring to the knowledge of good and evil,
so his offspring are innocent,
(or not held responsible,) till they arrive at a capacity to partake of this knowledge.
This will apply to idiots also, as well as children.--Rom. 4:15; v. 13.

Another point of doctrine with which I was then much tried,
was that of election and reprobation,
which opened to me thus:--Christ was the elect and chosen of God,
for the salvation of mankind; He was offered to all men by a manifestation of his Spirit;
and all those who joined in with this offer, and thereby became united to Him,
became in Him the elect of God;
and that God had predestined to a separation from himself,
all those who rejected this offer, by refusing to receive him;
and that this (the election as well as the reprobation) included all,
even those who had never heard of Christ`'s appearance in the flesh.
Thus was my mind satisfied in this respect also; and I now began to see clearly,
that I never could comprehend the things of God, but by the Spirit of God:
this induced me in every difficulty,
to wait in humility and dependence on the fresh openings of Truth.

About this time the Lord showed me that I must acknowledge Him more openly;
that I must not only overcome that unwillingness to let
it be seen that I was religiously exercised,
but also testify to others of his goodness to me.
Indeed, my mind was frequently so clothed with love to mankind,
that I did not much resist this opening: only I felt myself very unfit for it,
and prayed that He would better prepare me, and give me a clean heart and a right spirit;
and then I covenanted with Him to do any thing which he saw meet to appoint.
But, notwithstanding my professed willingness to be what the Lord would have me to be,
I was exceedingly afraid of deception,
and of mistaking something different for the Lord`'s requirings;
and this fear prevailed so much, that I durst hardly go to meeting, and when there,
was fearful of turning my mind to a right exercise,
lest something should be presented for me to say.
The Lord was then displeased with me, and let me see that my heart was deceitful,
and not right in His sight; that this fear was caused by self-will;
and in displeasure He seemed to leave me.
Greatly did I now bemoan my situation, and in deep sorrow and repentance,
did I entreat Him to return and strengthen me,
promising to strive against that fearfulness.
In mercy He inclined his ear, and shortly afterwards in a meeting,
impressed my mind with a few words, accompanied with such an impulse,
as I had not before felt;
which left me no doubt that the Lord required me to express them.
After having done so, my heart was so filled with peace,
that it seemed not only like a vessel full, but running over with praises to the Lord,
who had thus strengthened me to do his will:
for though it was a very little simple matter that was
thus brought to my mind I scarce know how,
yet, "`as the wind bloweth where it listeth, and thou hearest the sound thereof,
but canst not tell whence it comes nor whither it goes,`" so
appeared to me the influence of the Spirit,
with respect to that little offering;
and so it has been ever since with respect to
communications in the line of gospel ministry.

From this time my heart was dedicated to the Lord and his service, being desirous,
above all things, to know and do his will;
and though I often fell short through weakness, yet the Lord, in his unspeakable mercy,
did not leave me, but corrected and restored me again to favour;
so that I have great cause to praise Him, for by his rod, as well as his staff,
He hath comforted me.

I continued to express a few words in meetings, when thus impressed,
and was favoured with the answer of peace;
and as I carefully attended to the impulse or motion of the Spirit,
my gift gradually increased, and faith was given me to stand up,
even when I felt only the impulse, and very few words were presented to my mind;
but matter would sometimes flow to my admiration,
and to the enlargement of my communications.

My first appearance as a minister was, I believe, little expected by most Friends; yet,
as far as I ever understood, they were generally satisfied.
From the love I felt to flow to the people,
I was sometimes desirous that something might be given me to say to them,
but these desires were generally disappointed; it was shewn to me they were wrong,
and had their origin in self-will, and were to be rejected;
and that gospel ministry should be exercised and in
great simplicity and resignation to the Divine will,
without human labour or creaturely contrivance.
Thus I was instructed to wait in humble dependence.

In a short time, my faith was more particularly tried,
for the Lord was pleased to withdraw the gift +++[+++of the ministry]
for some time, I think about six months, so that I had nothing to communicate;
in this time, did the enemy endeavour to mislead me,
by presenting to my mind such specious openings and fields of doctrine,
that I was sometimes nearly deceived; but the impulse was wanting,
which I had been convinced was as the voice of my true guide,
and without which I durst not move: but the enemy endeavoured to imitate that also;
in this attempt, however, the counterfeit and the snare were more manifest.
Though the Lord was pleased to permit me to be thus tried,
in his great mercy and by his own invisible power he preserved me
from yielding to any of the temptations with which I was assailed;
and often at the close of meetings, when I had been thus tempted,
He filled my heart with thankfulness: in His own time however,
he returned with that sweet simple evidence, which had been my unfailing guide,
and which continues to be so to the present day.
I have been the more particular in my remarks on the ministry,
knowing that many snares are laid by the enemy,
even for such as have made a right beginning; and to those so tried,
my experience may perhaps afford some instruction.
If such an one should see this, I would say to him, "`I entreat thee never to move,
without that fresh feeling of the Divine impulse, which was thy guide in the beginning,
whatever fields of doctrine may be spread before thee,
or however clearly thou mayst see the states of the people.`"
It is not always necessary to speak, when we see things;
but we must sometimes conceal the vision, and always wait the Lord`'s command:
if we do otherwise, we shall lose our guide, and be involved in confusion.

My beloved wife had, before this time, come forth in public testimony as a minister;
which was a great comfort to me.
Being now enlisted in earnest, in a while I conceived it my duty to leave home,
and visit Friends in their meetings: this I performed in several counties in England;
and was also frequently engaged in visiting Friends`' families in different places:
and though I felt myself a very poor, weak, insignificant servant,
yet I had often to adore the goodness of God,
in condescending so to enable me to serve him, as to obtain peace.

About this time, (1783,) a very trying exercise came upon me,
from an apprehension that the Lord called me to
leave my native country and near connections,
and go to reside in Scotland.
The prospect really looked very discouraging.
There were few Friends at Edinburgh,
which was the first place pointed out to me;--I had a young family,
and how to provide for them I could not tell.
But, after some secret struggles,
my mind was relieved through resignation to the Divine will;
and I felt greatly encouraged by my dear wife`'s informing me,
that she also had a similar prospect: she knew nothing of mine,
as I had kept it to myself; but when we came to open our views to each other,
and found them so much in unison, our faith was strengthened.
But when we informed some of our near connections of our prospects, it was different:
my valuable mother discouraged us much at first;
setting before us the disadvantages of bringing up a family,
where there were so few Friends,
and how our children would be exposed to mix with the people in marriage, etc.
In a short time, however, she acknowledged that what she had said,
in the way of discouragement, had occasioned her much uneasiness,
and that she saw it had originated in her unwillingness to part with us;
that she could now say, "`Go; and I believe the Lord will go with you.`"
Thus was way gradually made for us in the minds of our relations and friends,
and to Scotland we came with our seven children in the year 1784.
In this country we have had many and various exercises,
many removals from one place to another, under an apprehension of duty;
but though we have been like pilgrims,
the Lord has in his abundant goodness fully satisfied us,
that our coming was in the way of our duty.
He has been truly our Shepherd, and we have not lacked.

+++[+++My dear father has not left any record of this period of his first coming to Edinburgh,
but it is known to have been one of peculiar trial and difficulty.
There were at that time but very few in profession with Friends,
and even of this small number,
the greater part had so much departed from their principles,
and had become in their manners, their language, and their dress,
so conformed to the fashions of the world,
that there was little or nothing left to distinguish them; and in this state of things,
as might have been expected, the discipline of the Society was scarcely supported at all.
Monthly Meetings had ceased to be held,
and it could not be ascertained who were or were not entitled to membership.

During this time of deep and painful exercise, his faith in his Almighty helper,
whose cause he had espoused, was mercifully sustained; and being enabled to persevere,
his labours were ultimately blessed with considerable success.
By the assistance of some Friends in the ministry,
who were drawn to visit this nearly desolate part of the heritage,
the discipline was before long, measurably restored,
and a few well concerned Friends raised up to conduct the affairs of the Society.
Among those who laboured in this work of reformation,
were our valued friends George Dillwyn of America, who was then residing in England,
and Henry Tuke of York, who visited Edinburgh about this time.

At Aberdeen and its neighbouring meetings, the state of things was also very discouraging.
It is true, they had not ceased to hold Monthly Meetings,
but the right exercise of the discipline was inefficiently supported;
and in order to its revival, it was found needful both there and at Edinburgh,
to make up lists of such as might be considered members or claimed to be such.
During his first residence in the neighbourhood of Edinburgh,
he occupied a small dairy farm about two miles from meeting;
but his stay here was but of short duration.
In about two years, under an impression of religious duty, he moved to Aberdeen,
where during his stay there, about two years more,
he opened a small grocery shop for the support of his family.
In the early part of the year 1788 he left Aberdeen,
and went to occupy a farm about fourteen miles farther north, near Kinmuck meeting;
and when not absent on religious service, this continued to be his home till 1794,
when he left it to pay a visit in the love of the gospel to Friends in America,
as stated in his own account.

It appears,
he received a certificate from his Monthly Meeting in the Eleventh Month 1789,
to visit Friends of the Quarterly Meeting of Cumberland, and the Meetings adjacent.
This visit, of which he has not left any account, was performed chiefly, it is believed,
on foot; as were also many of his journeys to attend the Half-year`'s Meeting,
in travelling to and from Edinburgh.
He has been heard to say, that he and his companions when on some of these journeys,
after walking as far as they were well able, were refused lodgings at some of the Inns,
partly from their not appearing like profitable guests,
and also on some occasions from the remains of a prejudice against Friends,
which many in that day still entertained.
The distance from Kinmuck to Edinburgh is upwards of 120 miles.
