== Chapter III.

[.chapter-synopsis]
* Travels In America in the Years 1794 to 1797

+++[+++They landed at Boston 23rd of Ninth Month;
but an affecting accident happened on board the ship on the preceding day,
which cast a gloom over the passengers and ship`'s company.
John Wigham notices the event in a letter to his wife, in nearly the following terms:

[.embedded-content-document.letter]
--

"`A melancholy accident happened on board our ship last night; one of the sailors,
a brother of the Captain, fell from the top-gallant yard into the boat on the deck,
and was killed instantly.
There was no storm at the time, nor any other known cause,
but it was supposed he had missed his hold.
It was an alarming circumstance to us to be called up in the night about 12 o`'clock,
with the striking intelligence;
and our tender-spirited young women were almost overcome with grief on the occasion.
The body was brought on shore to be buried this afternoon.`"]

--

After attending the week day meeting at Boston on the 25th, I left it on the 27th,
and reached New Bedford the same evening; attended the Meetings there on the First day,
and on the four succeeding days;--had meetings at different places,
was at the Quarterly Meeting at New Bedford,
and again at their usual meetings on First day.

5th of Tenth Month.
Second day, had a meeting with the towns-people;
and on the following day one across the river in the Presbyterian Meeting-house.

8th. Embarked for the island of Nantucket; arrived about midnight,
but did not reach my lodgings till two o`'clock in the afternoon,
being detained by a young woman, one of our passengers, taking fits:
I could not leave her till I saw her better.
She lay in this state for about four hours;
when she recovered and walked home leaning on my arm.
I called to see her next day; and with her, her mother, and several sisters,
I had a religious opportunity, which proved a tendering time:
they did not belong to our Society.

12th, First day.
I attended the South meeting in the morning, and the North in the afternoon;
and in the evening had one appointed at the
South house for the members of both meetings.

Second day.
Embarked for New Bedford, which I reached the same night,
accompanied by David Sands and dear Lydia Rotch,
the latter came over to be the companion of Martha Routh in her travels:
on Third day morning they set off towards Boston.
We had been nearly united as fellow-labourers, and our parting was a close trial to me:
in which I believe they felt much sympathy,
for I was not at that time favoured to see which way to move.

On Fourth day, I attended a meeting at Acushnet,
and on Fifth and Sixth had meetings at Long plain and Falmouth.
On the Seventh day, rode to Paul Wing`'s, where I lodged.
In this family were five precious daughters, Hephzibah, Beulah, Content, Tryphosa,
and Lydia, and several sons, who appeared hopeful; among whom, with their worthy parents,
so sweet a spirit seemed to prevail, that the house felt like a paradise.

19th, First day.
Attended their meeting at Sandwich,
and at the close gave notice of a meeting at 4 o`'clock in the afternoon,
to which Friends were requested to invite their neighbours; of whom a good many attended,
and it ended to satisfaction.

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife.

[.signed-section-context-open]
Providence, Rhode Island, Eleventh Month 5th, 1794.

Though I am pretty far from any seaport,
and not conveniently situated to get a letter forwarded to thee,
yet knowing how acceptable it will be to thee and our dear children,
to be informed that I am well, at least as well as usual,
I am desirous to make the attempt +++[+++to convey to you this intelligence.]
I wrote thee from Boston on our landing,
which I hope thou mayst have received before now;
but at that time I could not give thee any account of the line of my movements.
I may now inform thee, that, as far as I see at present,
I am likely to continue in New England during this winter.
There seems as much to do in these states (of New England,) as
I shall be able to get through before the ensuing spring.

I have been much stripped, and sometimes very low;
yet through unspeakable mercy I have been helped hitherto to get along,
so as that I hope the Truth has not suffered;
and I have at times been favoured with an undoubted evidence,
that I am in the way of my duty: and should it so please the Almighty,
that my body be laid down in this land, I desire to be content with His will,
and I hope thou wilt be so too; though I can say in truth, that I never loved thee more,
nor felt thine and our dear children`'s welfare dearer to me,
than since our present wide separation.
But, my dear Lord has given me an unshaken evidence that He will take care of you:
if you cleave close to Him, and make Him your confidence,
He will never leave nor forsake you.

Tell my Amos +++[+++his eldest son]
to take care of himself, not only as respects his bodily strength, not to over-do it,
but also in an especial manner regarding his conduct in his transactions among men,
that it may be upright in all things;--and in every
matter of moment to have recourse to the Monitor,
to mind the dictates of the Spirit of the Truth; so that whatever suffers,
the Truth may not suffer.
Tell him to keep close to meetings, let no work hinder him;
but let him so contrive his matters,
that they may give way to this important duty:--
and if he give up his heart to serve the Lord,
He will bless him in his endeavours.
And thou my dearest,
I wish thee not to overcharge either body or mind with the things of this life;
for indeed we often find the truth of the declaration,
that by taking thought we cannot add one cubit to our stature.
The Lord knows what things we stand in need of;--may He bless thee with a peaceful mind,
and be near to support thee in every trying time.

To my dear children, how do I feel my heart filled with paternal love to them all!
--and renewedly so,
at this time while I am writing.

--

+++[+++From the preceding period till the 1st of Twelfth Month,
John Wigham was diligently engaged in gospel labours; having,
as appears from his memoranda, rode 378 miles, attended thirty-five meetings,
several of them appointed for those not in profession with our religious Society;
besides visiting the families of Friends at Sandwich.
Arriving at Richmond, he attended a Monthly Meeting there,
and thus proceeds with his narrative.]

[.small-break]
'''

Twelfth Month.
After the Monthly Meeting at Richmond, I attended an appointed meeting the following day;
thence proceeded to Hopkintown, Westerly, South Kingston, New Meeting House.
First day, was at a meeting on an island, called Connanicut,
after which crossed to Rhode Island, and attended the afternoon meeting at Newport:
lodged at Jonathan Green`'s. Second day,
was at Portsmouth meeting on the north end of the island,
where were a large number of Friends:
there was but little given me to communicate among them,
and the preceding meeting at Newport was held altogether in silence.
Here I was glad to meet with Rebecca Wright;
and on Third day was favoured with her company to a
meeting at a place called Tiverton on the Main;
after which I rode to Jeremiah Austin`'s.

Fourth day.
Had a meeting at Little Compton, where I again had the company of Rebecca Wright,
as a fellow-labourer: a large number of people attended,
among whom was a Presbyterian minister and most of his flock: it was,
through Divine mercy, a pretty open time.
After meeting, the minister came and very respectfully offered me his hand,
and invited me to his house.
Rode to New Bedford, where I met with a kind reception;
the Friends seemed glad to see me, and to some of them I felt nearly united.
The receipt of a letter at this place from my beloved Mary R , and one also from P. Wing,
were strengthening and reviving to my poor mind.

11th and 12th of Twelfth Month.
Attended the Quarterly Meeting, and the 13th rode to Rhode Island,
where my mind was bound to visit families; in which my beloved friend, Isaac Layton,
was my companion.
There were 120 families on this island and at Connanicut;
and visiting these kept us engaged till the 7th of First Month, 1795.

8th of First Month.
I went thence to the Quarterly Meeting at Swansea, where I met with my beloved sisters,
Martha Routh, Rebecca Wright, and Lydia Rotch.
We were favoured to rejoice together in gospel fellowship.

After attending this Quarterly Meeting,
I proceeded under a weighty concern of mind to Longplain, finding that to obtain peace,
I must visit the families there, and not only those of our Society,
but also a number who had gone with Timothy Davis, and set up a separate meeting.
The exercising painful labour that I had among them,
will not I believe be easily forgotten.
The Lord in mercy, in the extending of His power,
favoured me with ability to clear myself;
and I trust many of them were left in some degree humbled and broken down.

On Fourth day, went to Cushnet week day meeting;
and the following day returned to that at Longplain,
where I was favoured considerably to relieve my mind.
The aforesaid Timothy Davis, a preacher among the Separatists,
and many of his adherents were at the meeting;
and their states being through holy help clearly spoken to, it ended, I think,
to the satisfaction of those rightly disposed.
When the meeting was over, a Judge named Spooner sent a message,
requesting me to go and see him; I did so,
and had a favoured time in a religious opportunity in his family;
they were kind and respectful, and their minds seemed softened.

I wrote a letter to Timothy Davis, exhorting him to humble himself,
and return to the Lord and His people.
I went the same evening to Cushnet, and on Sixth and Seventh days visited families,
and attended their meeting on First day.
On Second day, I went to Poneganset Monthly Meeting; returned to New Bedford,
and attended their Monthly Meeting on Third day, the 19th of First Month.

After this time, I was much tried, for want of clearness of prospect,
as to my future movement; and when some light did appear thereon,
I found some difficulty in becoming willing to yield to my impressions of duty:
my mind was drawn towards Nantucket.
I had already been there, and besides Martha Routh and Rebecca Wright were there,
and reason suggested that they were sufficient.

I stayed at Bedford over Fourth and Fifth days,
and on Sixth day I thought the way was a little
opened to go to Poneganset and Slocum`'s Neck.
Joseph Austin went with me,
and we appointed a meeting at the latter place on Seventh day:
a good many people attended.
The Lord favoured me with strength to discharge myself pretty fully,
and the meeting ended to satisfaction.

First day.
Attended the meeting at Poneganset in the morning;
in the afternoon rode to New Bedford to attend the meeting there;
and still feeling constrained to go to Nantucket, on the 2nd of Second Month,
I embarked on board the packet, and landed there next day.
Here I found dear Martha and Rebecca in the same situation as
I had been in on the other side of the water.
Martha told me that her way had been quite shut up,
and though she had been willing to visit families, and had mentioned it in meeting,
yet she had now no freedom to proceed.
I told her the state of my own mind,
and that I thought we must undertake the family visit together, which,
accompanied by Rebecca Wright, we accordingly began next day.
The Lord was pleased to own and encourage us in the service;
but after visiting a few families, Rebecca finding, as she said,
that it was not her business, left us: we parted in tender love and fellowship,
desiring each other`'s preservation.
We were sometimes accompanied by William Rotch, sometimes by Elizabeth or Lydia:
we were helped onwards from time to time,
and have great cause for thankfulness to the Lord,
who was our strength and our dependence.

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. Wigham.

[.signed-section-context-open]
Sherburn, Island of Nantucket, 16th of Second Month, 1795.

I can thankfully tell thee, that through mercy I have been favoured,
since my arrival in this land, with a better state of health, than when I left England;
I have only been stopped from travelling one afternoon on account of illness.
I have no certain companion in the ministry, now one and then another;
though it did seem desirable,
when I first landed to have met with a Friend under a similar concern to mine;
but none has yet been provided, though I have not been without company.
The Lord hath hitherto been my helper; I have lacked nothing;
if He be graciously pleased to continue His preserving
and supporting power to abilitate to do His will,
it is all I desire or ask.

I often remember thee, as well as the rest of my dear children,
with strong desires for your preservation, not only in the innocency of children,
but that as you grow in years you may grow in grace, from stature to stature.

My dear,
dwell deep;--feel after the life:--don`'t be content with a superficial conformity,
to moral rectitude, but feel after the pure substance of religion;
that makes and keeps the heart clean.

--

After going through the families +++[+++upon the island,) and
attending both their Monthly Meetings,
we felt our minds clear; and on the 23rd of Third Month, embarked in the packet,
accompanied by many Friends going to the Quarterly Meeting at Sandwich.
Landed at Woodshole,
from whence William Rotch intended to drive Martha
Routh and Lydia Rotch in a wagon with two horses.
I had purposed to go by water to New Bedford, where my horse was;
but the boat having run aground, and seeming likely to be detained all night,
I concluded to accompany them, and send for my horse to meet me at Sandwich.
At this, Martha Routh, and especially dear Lydia seemed much pleased,
and the latter pleasantly remarked, as she was stepping into the wagon,
"`I have got my wish:`"--but to her no small mortification,
one of the horses refused to go, and we were all obliged to give it up for that night,
and wait to procure another horse next morning.
They remained at the inn, and I returned on board the packet, where I slept comfortably.
When the tide rose she was got off, and about ten o`'clock we arrived at New Bedford,
where my friends and I were mutually glad to meet; reciprocal love united us.

25th. Left New Bedford in company with a number
of Friends going to the Quarterly Meeting,
and arrived at Paul Wing`'s in the evening.
To this family I felt united, and we were mutually glad again to see each other:
as "`iron sharpeneth iron, so doth the countenance of a man his friend.`"

Attended the Quarterly Meeting at Sandwich,
and also their meeting for worship on First day, which occupied me till the 30th;
and after having a few more meetings on my way, on the 3rd of Fourth Month,
I attended Longplain Monthly Meeting, to which Timothy Davis sent an acknowledgment,
expressing much desire for a reconciliation.
The Lord was pleased to own us, Truth prevailed,
and the opposing spirits were restrained, so that everything passed off quietly.
I was truly thankful, for it had been cause of great concern to me;
and Friends were comforted in the hope,
that this painful breach would be satisfactorily made up.
After meeting, I parted with dear Martha and Lydia,
who set out to New Bedford that evening.
We had been nearly united in gospel labour at Nantucket, and the meetings since.
I was now left without any companion;
but the best of companions was near to afford me support.

Joseph Cloud, a minister from Carolina,
going to visit Friends in the eastern parts of New England:
he and I were desirous to join as companions, and partly concluded to do so;
but after attending a few meetings together,
we both felt more easy to separate for the work`'s sake,
though in opposition to our personal wishes;
and two Friends whom we consulted on the subject, having also thought it best,
we parted in much love, and with sincere desires for each other`'s preservation.
He set off to Pembroke: I was again left alone.

A few places opening in my view to have meetings at, where no Friends resided,
and Obadiah Davis kindly offering to accompany and assist me;
we went to Rochester where was a meeting house, but none of our Society.
We had a pretty large gathering of people,
and through Divine favour it proved an acceptable time.
After meeting rode twelve miles to a tavern called Monument, where,
next day being the First of the week, we had a meeting in a Presbyterian meeting-house.
As that day they had no preacher, and notice having been given,
a large concourse of people attended; whose behaviour was becoming,
and some of them were affected to tenderness.
Dined at the house of a Presbyterian, who with his wife received us with great kindness.

6th. At a meeting in the evening at Sandwich, held also in a Presbyterian meeting-house;
the attendance was large,
and they seemed to me to be a people seeking after the pearl of great price; and,
through holy help, I was enabled to direct them where their souls might be satisfied.

7th. Proceeded to Rochester,
where notice was given of a meeting to be held in the Court House the following day.
After a few had assembled,
a company of the higher rank came and requested
us to go to the Presbyterian meeting-house,
which they said was close by, and would accommodate us better.
I should have preferred remaining in the Court House, but the people were so urgent,
that I thought it best to yield to their wishes, and complied.
It was through mercy a satisfactory time.
Though I have often had the use of the
meeting-houses belonging to other religious societies,
yet I prefer a Town Hall or any other public building, when it can be procured.
There is a difference, however, between this country and Old England;
their meetinghouses here are at the disposal of the people,
and they do not seem to be under any fear of offending
their ministers in granting them to Friends or others;
and in proposing a meeting, I have frequently left it to themselves to appoint the place,
that I might not bring Friends under obligation.

These public meetings have been upon the whole very awful to me,
feeling so very inadequate to such undertakings; and I have often thought,
that if the people knew how poor a creature I am, few would attend,
and I have at times been ready to conclude in my own mind, that if this was over,
I would take care not to venture again: nevertheless, the Lord`'s power has,
from time to time, made me willing to yield to the manifestations of duty,
and I trust so helped me in the needful time, that the cause of Truth has not suffered;
and if He continue so to do, I cannot but admire His condescension,
and humbly praise Him to whom alone all praise is due.

23rd. Reached Meadowsburgh,
having had many meetings at different places on my way thither; and after meeting there,
still accompanied by my kind friend Obadiah Davis, I rode, a good deal tired,
to Elijah Jenkin`'s, hoping to get a good rest;
but I was kept awake most part of the night,
by an exercise about having a meeting at a village we had passed, about five miles back,
where there is no Friends`' meeting.
In the morn ing I yielded to it, seeing no other way to obtain peace.
I mentioned the subject to my companion and the Friends of the house,
they thought it might be arranged; and we accordingly set out after breakfast,
and on reaching the place, proposed the matter to some of the principal people.
They offered the Baptist meeting-house which we accepted,
and appointed a meeting at five in the afternoon.
Through Divine favour my mind was greatly relieved:
some of the people expressed much satisfaction with the opportunity,
and I felt humbly thankful to the Father of mercies;
indeed I can never feel sufficiently thankful for His
condescending goodness to a poor unworthy creature.

Since I undertook this eastward journey, I have had several large meetings,
attended by many of other religious societies,
which frequently caused me to feel great fear,
lest I should do anything to dishonour the cause of Truth;
but the Lord has hitherto helped me,
and often in His unspeakable love caused the gospel
message to flow forth freely to the people,
and contrited many hearts by His power.
May His name be ever praised, honoured, and adored;
and may I become more and more devoted to do His will!

We have found here and there among Friends a little remnant of true travellers,
though great carelessness is too prevalent;
but the Lord is at work in the hearts of the people, calling home the wanderers, and is,
I believe preparing himself instruments among the youth,
for whom my mind is often deeply baptised,
and sometimes I am engaged to minister to their encouragement.
May the Lord be pleased to strengthen them, is often the earnest prayer of my heart.
Stayed over First day at Berwick.

The next day rode to a place called Desert; had a meeting at five in the evening,
at the house of a friendly man, who with his wife had been a Baptist;
but now opens his house to a few tender-hearted people,
partly convinced of our principles,
who are not easy to meet with the Baptists or Presbyterians,
and therefore assemble to worship in silence.
I had a satisfactory meeting with them, and left them in much tenderness and love.
Next morning had a satisfactory meeting at a Baptist`'s house;
thence attended meetings at Portland and Falmouth, and afterwards went to Windham,
where I unexpectedly met with Joseph Cloud, whom I was glad to see,
my mind being very low and almost overcome;
but meeting with an exercised brother a little refreshed me.

1st of Fifth Month, 1795.
Had a meeting at Windham,
where the Lord was pleased to open counsel to several different states,
and to give ability to communicate it with a considerable degree of clearness;
through Divine favour it was a satisfactory meeting.
A meeting at Durham was held in silence, except a few words at the close,
informing the people that in accordance with the apostles`' experience,
we were sensible that of ourselves we could do nothing,
but were only required to communicate what the Lord gives for that purpose.
I could discover in some of the people dissatisfaction at the want of words,
but I felt peace, and was satisfied with bearing my testimony to silent worship,
by example as well as precept.
Had a satisfactory meeting at Bath, the people chiefly Baptists; thence to Broad Cove,
forty miles of bad road, was much tossed;
I was kindly received by one who had lately
joined Friends as well as by his wife and family,
who were not of our Society.
Had a meeting next day at Cornelius Roads`'; the succeeding one,
(Seventh day,) visited some families.

First day, 10th. Had two meetings,
one at Cornelius Roads`' and one at a widow`'s house at the head of the bay.
Several of the people here seem tender and convinced of the Truth,
but stumble at the cross.
I felt satisfied with visiting them, sympathizing much with some of the young people,
children of parents who had been many years convinced, but continued in weakness,
having for want of faithfulness, made little progress in religion, and I fear,
proved rather a cause of stumbling than of assistance to their children.
I felt very reluctant to leave them.

[.small-break]
'''

+++[+++First day,
24th. During the preceding two weeks he appears to have travelled on horseback, on foot,
and by water, 189 miles, had about fifteen meetings,
besides attending a Monthly Meeting at Wasselburgh.
His narrative proceeds:--]

[.small-break]
'''

At Been`'s Green we lodged with Cyrus and Mary Dean,
who entertained us kindly in a little log-house; though poor as to this world,
yet they are rich in love and good works,
which made their abode a sweet comfortable lodging place.
They were convinced Friends,
and had been the means of convincing several of their neighbours;
and a lively little meeting was settled there.
Went next to Lewistown.
The meetings have been small since we left Wasselburgh;
but the neighbours of other religious societies seem inclined to attend,
and appear seeking after the right way.
The Lord was pleased to give and enable to communicate matter,
which I believe was suitable to their states.
At Stoney and Green in particular, there are a few nearly convinced Friends,
of sweet spirits; through whom,
the influence of Truth seemed to me to be attractive to the people around them.

Attended the Quarterly Meeting at Falmouth on the 27th and 28th. The meetings for
worship and discipline held from eleven till half-past five o`'clock,
by which I was much exhausted.
Next day, I proceeded to Berwick, where, and at several other places, I had meetings;
I also attended the Quarterly Meeting at Salem, held on the 3rd and 4th of Sixth Month.

7th of Sixth Month.
Reached New Bedford, where to our mutual pleasure I met my dear friends, Martha Routh,
her companion Lydia Rotch, and Samuel Smith from Philadelphia.

8th. Accompanied by many Friends, went to the Yearly Meeting on Rhode Island.
I attended its several sittings, and also a public meeting held at Portsmouth.
Here I met my beloved friends, Deborah Darby, and Rebecca Young--strangers like myself.
Through Divine assistance we were sweetly united in gospel labour,
by which we were endeared to each other; and when the time came for us to be separated,
each to our several allotments of duty, our parting proved a solemn one.

[.small-break]
'''

+++[+++Being joined by his friend, Samuel Smith, as companion, they travelled together,
and held many meetings, through a rough country, where the roads were difficult;
and the weather being very hot,
Samuel Smith finding himself unequal to the exertion of proceeding further,
left John Wigham at Richmond, and turned towards Rhode Island.]

[.small-break]
'''

12th of Seventh Month.
I set out towards the Cohons`' Country with a Friend named Israel Saby, as guide.
In two days, travelling ninety miles, we reached a place called Sharon.

15th. Had a meeting in a Friend`'s house at Strafford.
Most of the people living near are Baptists, by some called Quaker-Baptists.
They express a great desire to associate with Friends,
and claim a kind of kindred with them, professing to hold the same sentiments,
except on the point of baptism:
but I thought there was among them much of a creaturely activity,
without sufficiently seeking for that sanctifying influence,
under which spiritual worship is performed.
One of their preachers prayed in our meeting, during which Friends kept their seats,
at which some of the people seemed dissatisfied; one woman in particular,
did not forbear to express it.
I spoke a few words shewing the reason why we could not
unite in prayers offered in the time and will of man;
I likewise told her I was a stranger,
and did not know whether the person was a member of our Society or not,
but I felt an evident stop in my mind, which prevented my standing up.
The people generally appeared satisfied with my explanation,
and some of them expressed their satisfaction: the preacher said nothing.
I was glad that I was present,
and had an opportunity of bearing testimony against their unauthorized activity.
A Friend told me afterwards,
that he hoped it would be some check to their speaking in Friends`' meetings,
with which they had been much tried.

After attending a meeting at Sharon, I set out for Fraserburgh,
reached Thomas Robinson`'s at Virginia,
much exhausted by riding seventy-five miles in the heat, through a rugged country,
over what is called the Green Mountain.
We were four hours in going eleven miles,
being often obliged to alight and lead our horses,
the hills being so steep and the woods so thick.

19th, First Day.
Attended meeting at Fraserburgh: next to Moncton and the Grand Island, as it is called,
where a few Friends are settled.
In getting there, we rode a mile in water so deep, as to be above the tops of our boots,
and in this wet condition we had to ride eight miles before we reached a Friend`'s house.
Next day had a meeting, then went ten miles in a canoe, and walked seven to Peru.

23rd. After a meeting at Peru, returned as before by land and water, to Grand Isle.

24th. Returned to Fraserburgh.
We have had hot weather, bad roads, and poor accommodation in small log-houses,
in some places very poor beds.
The people in these woods seem to have some sense of religion:
but they live in a very rough slovenly manner,
many of them having settled here when very poor, retain their slovenly habits,
even now when they have got plentiful estates.
Few of them, either men or women, wear shoes in the summer.
The men wear trousers and shirts of coarse linen, often with their collars open,
and without neckcloth; and being sooty from working among the burnt wood,
they form a singular appearance as they come in
groups from their work to their little huts.
I often think that their manner of living,
ill accords with my dear sister Martha Routh`'s system--
of cleanliness and religion going together;
but much allowance must be made for the force of custom.
The Lord regards them in their low estate,
and there are some precious tender minds among them.

26th. Attended meeting at Fraserburgh; and one in the afternoon at Nicholas Holmes`',
six miles off.

27th. Set out for Danby; next day reached Stephen Rodgers`', a distance of seventy miles.
Here I stayed a day or two to rest, being almost worn out by travelling in the heat.

1st of Eighth Month.
Stephen Rodgers accompanied me to a place called Mount Holy,
with an intention of holding a meeting; but, on arrival,
we found that most of the people in the settlement being Baptists,
were gone to one of their Quarterly Meetings.
After some satisfactory conversation with two of their families,
we returned to John Bullon`'s, where we stayed over Seventh day.

3rd. First day.
Had a meeting in the forenoon in the Court-house at Rutland;
and one in the afternoon at the Presbyterian meeting-house.
Their minister is a Mulatto, a liberal man,--he attended the meeting,
and I believe most of his flock; it was a favoured time,
the Lord afforded ability to declare the Truth to the people, who were very attentive,
and some of them affected.
The nature of a free gospel ministry was pretty clearly opened;
yet the minister was respectful, and kindly invited us to lodge with him.
We acknowledged his hospitality,
but took leave and rode six miles farther to the house of a Baptist,
an acquaintance of Stephen Rodgers, who entertained us kindly.

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife.

[.signed-section-context-open]
Saratogo, Eighth Month 9th, 1795.

I received both my dear Eliza`'s letters yesterday, which were truly acceptable.
My heart feels very thankful for the favour of health conferred on thee and
our dear children:--you do indeed feel near and dear to my life.
How good is the Lord, who supplieth all your wants:--thou sayest you want for nothing,
save my company; and that thou knowest can do you no good,
if my proper place be elsewhere.
I have been favoured with health beyond my expectation;
although the extreme heat of this country is exceedingly trying to my constitution,
and I often feel much overcome by it: feeble and faint, I am very thin in flesh;
but on the whole, seem renewed day by day, so as to be able to keep on travelling,
not having been detained one day on account of illness.
I cannot do less than acknowledge with thankfulness,
that the Lord hath hitherto helped me,
(unworthy as I am,) to get along to a good degree of satisfaction.

The sun heats through the wooden houses, so that they feel like being in a stove;
and the flies are so numerous, they are exceedingly troublesome,
and as soon as daylight appears, I can obtain no more rest.
I have been as far North as Lake Champlain, and over it at a place called Peru,
adjoining Canada.
There are some settlements of Friends here and there all over the woods.
I have had long rides and bad roads for some weeks past;
but now have got where Friends are more thickly settled.

I have given thee a pretty full account of my bodily state; and as to the mind,
the varied exercises attendant on poor travellers,
thou knowest from experimental feeling,
better than from any description I can give with my pen.
Thou knowest what a poor creature I am, hobbling along much as usual.
I am frequently detained visiting families,
and having meetings among those of other Societies; so that I get on but slowly:
but I sometimes think perhaps I may not have to visit all America,
but in this I desire to be resigned to the Lord`'s will.
I believe I need not put thee in mind to pray for my preservation;--that cementing,
uniting sympathy, which subsists between us,
renders it impossible for us not to feel concerned for
the welfare of each other as for our own.

--

10th of Eighth Month.
First day, at Saratogo: I attended their meeting,
having held several others on my way hither.
I remained at the house of Thomas Welbert, over Second day.
Here I had the satisfaction of receiving two letters from my dear wife,
informing me of the welfare of my family, at which I was glad.
I spent the day in writing to her and some others.

11th. Arrived at Eastbourn, where I attended the Quarterly Meeting,
and had a public meeting with the inhabitants; and on the 15th proceeded onwards,
holding many meetings, till I reached Cornwall;
near which I lodged at the house of David Sands, which seemed like home,
his dear wife and daughters were affectionately kind,
and I felt sweetly comforted under their roof.^
footnote:[David Sands was at this time absent,
being engaged in a religious visit to Friends and others in Europe.]

7th of Ninth Month.
Had a meeting at Cornwall in the forenoon; and one at Clive in the afternoon.
Went thence over a mountain to West Point,
where I lodged at the house of a son-in-law of David Sands.

[.small-break]
'''

+++[+++Holding meetings by the way,
he appears now to have bent his course towards Philadelphia, at which city, he states,
he attended the Yearly Meeting and three Monthly Meetings.
On the 5th of Tenth Month, he proceeded to Baltimore, which he reached on the 9th,
having had meetings on his way thither at Derby, Centre, Kennet, and Wilmington,
previous to his leaving Philadelphia, he wrote as follows:--]

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son-In-Law, John Cruikshank.

[.signed-section-context-open]
Philadelphia, Ninth Month 29th, 1795.

I have often remembered thee and thy dear wife,
with affectionate love and fatherly solicitude,
greatly desiring your preservation and perseverance in religious pursuits.
Having believed you are called to be waymarks, to hold up an ensign to the people,
it has often been the prayer of my heart, that you may be so preserved,
that it may never be said of you, as it hath happened to Israel,
"`when a standard bearer fainteth.`"
If you, my dear children, be watchful and obedient in all things, the Lord will keep you.
He +++[+++the Shepherd of Israel]
neither slumbers nor sleeps;
and none is able to pluck his sheep out of His hand:--
if you do not yourselves turn away from Him,
no power can hurt you.
Take care that you prefer nothing before Him; for such as do so,
are not worthy of Him.--If he bring you into the furnace,
it is for your refinement:--if He proclaim a fast,
it is to make your appetites better:--if He dip you in Jordan, the river of judgment,
it is in order for your further washing;--and
all to make you more fruitful in those things,
by which His excellent name is glorified;
that you also may be glorified with Him in an endless eternity,
when these few fleeting days are over.
And truly, a termination to our earthly pilgrimage may soon come;
numerous are the instances of mortality now in this country,
not so much here as in New York, where a fever prevails,
similar to the one that raged in this city two years ago, of which I doubt not,
you have accounts in the newspapers.
Much sickness also exists in many other parts of the country, arising from fevers,
fluxes, etc., of which many die.

This has been considered a remarkably hot summer; and indeed it has felt so to me,
and I have been much overcome with it; yet through mercy,
I have been enabled to move along; and now the weather is cooler, I am as well as usual.
It is now the time of the Yearly Meeting here;
when it is over I expect to go towards Baltimore, and then during the winter to Virginia,
Maryland, and the Carolinas, whence, perhaps I may not have any opportunity of writing;
so that you need not think it strange, should you be long in hearing from me,
though I intend to write to some of you should any way open for it.

Give my dear love to my poor children;
I often think how they are left--fatherless and motherless,
and sometimes it feels pinching; but I hope He, whom we believe we are following,
will do that which is best for them; if they do not oppose His will;
and this they might do, even if we were with them.^
footnote:[At this period his wife had left her home on religious service.]

--

10th. Baltimore.
Attended the Yearly Meeting, which held five days;
had the company of Deborah Darby and Rebecca Young, whom I was truly glad to meet,
and we laboured together in much unity.
Had a meeting appointed on First day evening for the coloured people,
which was large and satisfactory.
Visited the prisoners in the jail, several of whom, both black and white, were in irons:
during our religious communications some of them were much contrited.
Stayed over First day; and on Second day went to Ellicots Mills,
where I had a public meeting.
Thence to Elkridge, Sandy Spring, Indian Spring, where,
and at twelve other places I had meetings.
I proceeded to Jennets, Richmond, Black Creek, and Wyon Oak:
these are all small meetings, and religion as to the life of it,
is at a low ebb in Virginia; there seems to be a root of corruption so deep,
that makes it hard work for the poor ministers to reach.
My labour among them seldom gives me relief,
and I have often to go from place to place heavyhearted and mourning on my way.

I now proceeded to Scirmons, then returned to Wyon Oak, Curles and Richmond,
where I had two public meetings;
the one in the afternoon was specially appointed for the blacks,
at which several members of the Assembly attended; some of whom, I understood,
were displeased at being so plainly dealt with in the presence of their bondsmen.
I was led to declare among them the universality of the love of God,
and the equality of his ways;--that Christ died for all men, of whatever colour,
and was willing to save them on the same terms of belief and of baptism, namely,
the washing of regeneration and renewing of the heart,
by the power and influence of the Holy Spirit.
I felt peace and satisfaction in the censure of these hard-hearted taskmasters.

[.small-break]
'''

+++[+++After leaving Richmond, he appears to have been again at Wyon Oak,
where he attended a Quarterly Meeting;
and on the 1st of Twelfth Month proceeded to Burley, Scarbrook, and Blackwater, where,
and at a number of other places, he had meetings without recording any remarks,
till coming to Lower Trent, his narrative proceeds:--]

[.small-break]
'''

I attended the meeting with dear Martha Routh and Lydia Rotch;
when the Lord was graciously pleased to unite us under
a renewed feeling of the influence of His love,
for which favour our hearts were lifted up to Him,
in thankful acknowledgment of His condescending goodness.
My companion, William Tremble, being attacked with gout and rheumatism,
had left me at Contentney, and returned home.
I felt lonely, but the Lord sustained me, praises be to His name!
I next proceeded to Clubfoot Creek and Corsound, and back to Contentney,
to attend the Quarterly Meeting.
There I again met with my beloved fellow travellers, Martha and Lydia;
and was truly refreshed by the unity of their devoted spirits,
and my doubtful mind strengthened and confirmed by our similarity of feeling.
We were detained several days by a flood; during which I often thought,
that after parting with them,
I should be "`like a sparrow alone on the house-top:`"--Lord be pleased to help,
as thou hast hitherto done!

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife.

[.signed-section-context-open]
Contentney, North Carolina, First Month 3rd, 1796.

Having met with an opportunity to send a line to Baltimore, from whence, perhaps,
this may be forwarded to England, I am willing to embrace it,
to tell thee that I am well; and have abundant cause to acknowledge the Lord`'s goodness,
even in supporting my poor weak body to travel about in this country,
where people at this time are so sickly;--scarcely a family where I come,
is free from ague, or some other disorder.
It is now the middle of winter, and yet the weather is so warm,
that it is needful to have all the doors and windows open in the meeting-houses.

I am getting about from meeting to meeting, often under discouraging feelings;
yet have no just ground of complaint,
having I trust been hitherto preserved from hurting the cause.

I often think on thee, my dearest, and our dear children,
with ardent desires for your welfare; I look towards you with sympathy,
but think I cannot help you, and therefore endeavour to confide in Him who can.

I see no end of my labours here yet; you must give me up, and do the best you can:
we serve a good Master; and I have sometimes strength to hope,
that He will take care of you, if you cleave unto Him.
May the Lord direct and keep you; there is no other Saviour.

--

[.offset]
+++[+++His narrative proceeds:]

The select Quarterly Meeting
at Contentney was held on the Seventh day,
a public meeting on First day, and the meeting for discipline on Second day.
Fourth day, I rode to Bonecreek, and had a meeting; after which I intended to go to Nuce,
but the river was so high it was impassable.
I therefore returned to Benjamin Arnold`'s, and stayed at this kind Friend`'s house,
till after First day meeting; then rode eighteen miles towards Nuce, crossed in a canoe,
the river being still too high to ford,^
footnote:[In fording one of the rivers in America,
he was apparently involved in considerable danger.
His horse fell when about the middle of the stream,
and he was consequently thrown into the water.
The horse lay on his side with his feet down the current,
and all John Wigham`'s efforts to get him on his feet again, proved in vain.
A person at the side of the river, to which he intended to proceed,
observing him in difficulty, called to him, attempting to offer some advice;
but the distance being considerable, he could not make John Wigham hear;
and seeing the critical situation in which he was placed, kindly rushed into the river,
waded to him, and seizing the horse by the bridle, drew his head round,
until his feet were against the stream, when he readily recovered his standing.]
and walked to meeting.

Set out for Smithfield, to a bridge twenty miles up the river; and when there,
found my mind most drawn to New Garden Settlement, so proceeded towards Eno meeting;
thence taking many meetings by the way, came to Centre to the Quarterly Meeting.
It was very large, and many persons of other societies, probably some hundreds,
came to the public meeting on First day; not as it seemed to attend it,
but to amuse themselves in companies about the meeting-house, never desiring to enter it,
nor even paying any attention when a Friend (Peter Yarnell,) was preaching.
A number of them came next day, while the meeting for discipline was sitting,
and were if possible more imprudent than before, looking in at the windows and door,
and refusing to go away when desired: but what most affected me was,
that several members of our Society encouraged them, by joining them in conversation,
in parties about the door.
In these parts, there is a lamentable neglect in the education of children,
and much that is formal and superficial; though there are a few upright labourers,
yet it seems to me they are almost smothered in rubbish.
Much pains were taken in this meeting to reform these abuses.
A committee was appointed, consisting of members of the different Monthly Meetings,
to have a care over the young people, particularly at these times;
and to endeavour to prevent their going out of meeting,
or associating with those troublesome people, who, it was hoped,
would then refrain from coming.

After this meeting, which was a trying laborious one, I went to Sherburn, Pinewoods,
New Garden, and Hopewell: at this last place,
I had a meeting with a people called Nicholites.
Thence to Muddy Creek, Blue Creek, and back to New Garden,
where we felt a concern to visit the families,
Peter Yarnell and James Emlen being now with me.
We visited in company eighty families in twelve days;
then attended the Monthly and Quarterly Meetings.
The latter, which was held the 12th of Third Month, 1796, was large;
but many seemed superficial professors, so that the few,
who dwelt low with the pure witness, had hard labour.

Proceeded to Muddy Creek,
where also we found we must labour with them from house to house.
We visited thirty-seven families.
Then taking several meetings in our way, we passed over the Blue Ridge to Chesnut Creek,
Reedy Island, and Burkforke.
Here I parted with Peter Yarnell and James Emlen, which was a trial to me,
as we had been knit together in true fellowship through some arduous labour.
I returned over the Blue Ridge, accompanied only by a guide, eighty miles to Goose Creek;
here I lodged at Christopher Anthony`'s,
which seemed like a change from savage to civilized life,
kind friends and a comfortable house, clean and meat;
especially when contrasted with the dwellings of the backwood`'s people.

[.small-break]
'''

+++[+++After leaving this comfortable abode,
he mentions having had a number of meetings on his way to Philadelphia; where,
to their mutual rejoicing, he met unexpectedly with his beloved sisters, Martha Routh,
Lydia Rotch, Deborah Darby, and Rebecca Young.
From this city he wrote to his wife as follows:--]

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife.

[.signed-section-context-open]
Philadelphia, Fifth Month 2nd, 1796.

On Seventh day last I arrived at this city, where I met with thy two letters:
I was glad of them,
(as it is more than seven months since I received one;) though some of the
intelligence they contained affected me;--so many removals by death,
and also thy concern about going to +++[+++reside in Edinburgh.
In this prospect I cannot help feeling much sympathy with thee,
well knowing how trying it must be; though I have no manner of doubt of its being right.
Our path through this vale of tears seems to be a singular one; but no matter,
if we land safe at last.
Be encouraged, my dear love, to faithfulness;--we know no other way to peace.
We find it necessary to dwell deep:--let us steadily continue
in the patience:--no matter how little or how obscure we are,
if we are near our Master.

Deborah Darby and Rebecca Young are here, preparing to embark for home;
by whom I intend to send this letter.
Samuel Emlen and William Savery, a Friend belonging to this city,
also two women Friends from the country, whose names I do not now recollect,
all intend going in the same ship, and expect to sail in ten days.
Deborah Darby and Rebecca Young, have, I believe,
laboured honestly and very diligently in this land,
and have left a sweet savour where they have been:--I hope
they may be favoured to reach their native land in peace.
Martha Routh is also here; I met with them all unexpectedly, which was very pleasing,
after a long wilderness journey in a very poor country to the southward.
I thought I felt excused from going to South Carolina and Georgia, at least at this time:
I have spent the last winter in Maryland, Virginia, and North Carolina.
Thou must endeavour, my dear, to keep in the patience;
there seems a large field before me, and when I shall get through I know not;
but I am as diligent as I am able to bear, and through favour,
as well in my health as when at home.
If I am longer in visiting America than some have been, do not think it strange;
Friends within a few years past are spread many hundreds of miles back into the woods;
and I have often been detained visiting families;--I suppose I have visited
six or seven hundred families;--I wish much to do what is required,
that I may find peace at last.

I often feel for thee and my dear children with anxious solicitude of soul;
and when I am labouring among young people, which has been much my concern,
I often remember, that I have left my own: but I am sometimes comforted in recollecting,
that I have committed them to the keeping of the good Shepherd; and a hope is with me,
that if they will be teachable children, He will care for them:
whether it be His will that we should meet in mutability or not,
if we meet in a better country, His will be done.

--
