== Chapter V.

[.chapter-synopsis]
* Visits the Western Counties of England, etc. in 1799
* Attends the Yearly Meeting in London in 1800
* Visits the Meetings of Friends in Various Counties on His Return
* Remarks on His Trials
* Religious Exercises and Providential Preservations
* Observations on the State of Society at Edinburgh, in 1806
* Visits Parts of Yorkshire, Lincoln`'s Hire, etc. In 1808, Accompanied by George Richardson
* With Same Friend as Companion,
* Visits the Meetings in and about London, and Some of the Southern and Midland Counties, in 1809
* Thoughts on the Nature Of Love, 1812

+++[+++Previous to his entering on the visit to the western counties,
of which an account follows, it appears,
John Wigham attended the Yearly Meeting in London,
as one of the representatives from the Half Year`'s Meeting for North Britain.
In the minutes of this Meeting, of date 30th of Fourth Month, 1798,
the following is recorded, viz.]

[.embedded-content-document.minutes]
--

"`Two certificates on behalf of our esteemed friend John Wigham, have been now read,
to our comfort and edification; and his company and gospel labours, have,
on this occasion, been truly acceptable, and for his peaceful return we feel thankful.
One of these certificates is from the Yearly Meeting held in Rhode Island,
for New England, in the Third Month, 1795,
and the other from the General Meeting of Ministers and Elders, held in Philadelphia,
in the Third Month, 1797.

--

In the Sixth Month, 1799, I set out on a religious visit to Friends,
in the western counties of England: my dear wife accompanied me, through Cumberland,
and then returned.

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son-in-law, James Glenny.

[.signed-section-context-open]
Edinburgh, Sixth Month 14th, 1799.

I am pleased to hear that you are favoured with health:--may
your hope and trust be in the arm of Omnipotence,
who is ever sufficient to those that faithfully serve Him;
we have abundantly proved that He is indeed a present help in every needful time.

An early dedication of heart to the Lord, is no doubt acceptable to Him;
to give up all into His care and keeping, and to look upon ourselves as stewards,
to be directed and ordered by Him,
is the safest way of steering through this uncertain pilgrimage.

The desire of my heart is, that my children may be the Lord`'s children;
and then I have no doubt, but He will be their shepherd, and they shall not want.

Yesterday was our Monthly Meeting,
when I ventured to mention a prospect I have of
a visit to Friends in some parts of England,
with which the meeting concurred; and I think of setting out next Fifth day,
and my wife thinks of going with me as far as Cumberland Quarterly Meeting.

After my dear wife parted from me, I proceeded through Westmoreland, Lancashire,
Cheshire, South Wales, by Bristol as far as the Lands-end in Cornwall;
and I crossed to the island of Guernsey, in company with my friend John Abbott.

--

[.offset]
+++[+++The three following letters were written whilst on his journey.]

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son-in-law, John Cruickshank.

[.signed-section-context-open]
Preston, Eighth Month 7th, 1799.

I have been helped along from place to place,
and been enabled to clear myself to a good degree of
satisfaction;--though I have visited many low spots,
many poor meetings, where little of the life of religion seems to be left,
the standard bearers weak and tottering,--and but few
Aarons or Hurs to support the feeble arms of such;
so that in many places the enemy seems to prevail, and threaten a total desolation.

The prevalence of a worldly spirit--how it weakens!
O! take care of its encroachments;--it is a lurking enemy; plausible are its baits,
and many are taken in the snare.
I often look towards you,
with desires that you may put on strength in the name of the Lord.
Strong and ardent is my solicitude for you, my dear children,
whom I have left in Scotland,
that you may be faithful warriors in the great cause.--
Remember me affectionately to my children,
James and Elizabeth; they are young: tell them, now is their time, now is their day,
to give up their hearts to seek and serve the Lord.
O! that they may begin at the right end,
seek first the kingdom of God and His righteousness,
and no doubt but other things needful will be added.
Remember me also to my Amos and Barbara,
tell them they are called and ought to be waymarks; if they mind their standing,
the Lord will not fail them.
May you all unite in true harmony,
as advocates for the one good cause--of spreading and advancing the
saving knowledge of God among the children of men,
helpers one of another, preferring one another in love,
knit together by a bond of love that can never be broken:
then will you shine in your day, and the enemy shall never be able to hurt you.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Ann Christy.

[.signed-section-context-open]
Coalbrookdale, Eighth Month 23rd, 1799.

Thy sensibility of weakness confirms my belief,
that thou art under the care of the great and good Shepherd,--
that thou art preserved sensible of what thou art without Him;
and thy fear will be as a fountain of life, preserving from the snares of death.
Thou still feels precious to me, I think the union grows stronger;
for which I am thankful:--nothing can break it,
but our departure from the foundation;--strippedness or
poverty of spirit has no tendency to lessen,
but rather to increase it; though we may not always feel it alike.
Every dispensation that reduces self, increases the spiritual union:
the bond is strengthened by obstructions being removed; and if we grow in grace,
we shall become less and less in our own eyes.
This, I trust, is in some degree our experience:
let us then each keep to our own exercise in our own particular gifts;
so shall we know an advancement in the performance of the Divine will,
until it becomes as our meat and drink.

I may inform thee, which I know will be satisfactory to thee,
that I have been helped along so far beyond expectation,
both as regards the body and the mind:--my poor body cannot endure much,
and my mind often feels inexpressibly feeble:
but the Lord in mercy has helped me from time to time with a little help,
to hobble on from place to place; and I hope He has preserved me from hurting the cause,
and that I may have been enabled sometimes to
administer a little encouragement to the honest-hearted.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Daughter-in-Law, Barbara Wigham.

[.signed-section-context-open]
Bristol, Ninth Month, 1799.

I feel inclined to address thee in this way.--I love thee as a daughter,
and I love thee as a sister in gospel fellowship;
and cannot but desire thy preservation and growth as my own.
I am sensible how needful it is to be watchful:--our strength
consists in our being preserved in the spiritual union;
and many things present themselves, which if not carefully watched against,
will obstruct that wherein our strength consists,
and by which only we can experience a growth.
There are right hand errors, as well as left hand errors,
of commission as well as omission; and to be kept in the path of true obedience,
is the desirable attainment:--to have the eye single,
is the way to have the whole body full of light.

A perfect resignation and willingness to be little, is the way to grow;
and when we do in reality grow in the Truth,
we shall become less and less in our own estimation; self will be weakened,
humility increased, and our hearts enlarged in love and gratitude to God,
and in submission to His holy commands.

Suffer me to remind thee of the apostle`'s exhortation: "`Mind your calling, brethren.`"
I know not that thou art any way deficient;--but knowing the wiles of Satan,
these things seemed to come before me, to express to thee; hoping that thou also,
in thy measure,
art exercised on my behalf--no one has more need of constant watchfulness than I have.

Thou hast known a passing through dispensations of deep trial,
hid from the knowledge of men;--the Lord has been thy stay in many a tempest, when,
perhaps, all around thought thee in quiet; He has seen all thy buffetings,
and has sustained thy tossed mind, when there was no other anchor;
He has heard thy groanings in secret places,
and bottled up thy tears;--and undoubtedly He will +++[+++in His mercy]
recompence the fruit thereof into thy bosom.
If thou continue in dedication to Him, and His service,
He will be thy bow and battle axe, teach thy hands to war, and thy fingers to fight.
Trust in Him then, and thou shalt never be confounded.

I got here yesterday from Wales, where I have had pretty hard travelling,
both for myself and my horse.
The weather has been wet, the roads bad, and the hay bad,
so that my horse has got much worn down; but I hope, as I am now in England,
the fare will be better for him, and the journeys shorter.

--

[.offset]
+++[+++To return to his journal.]

[.small-break]
'''

We visited the few families professing with Friends in the island of Guernsey,
and had some public meetings;
being kindly entertained and assisted by our valued friends, Nicholas and Mary Naftal;
the former was our interpreter.
The town (called St. Petersport) is an uncommonly bustling place;
I could not but be surprised at the hurry its crowded inhabitants seemed to be in,
and lamented it.
I took a lonely walk, and sat down by the side of a hedge over against the town;
my mind was gathered into a state of quietude; in which I felt content to be a pilgrim,
and a willingness, however insignificant, to be just what the Lord would have me to be:
and I renewedly entered into covenant to serve Him,
in the ability He might be pleased to afford, without desiring any conditions for myself;
for my whole heart was at this time so filled with love to Him,
so devoted to labour for the exaltation of His name,
that I thought I could not desire anything, or any enjoyment,
that would not tend to His honour.

"`O Lord! enable me to do thy will,`"--is my only petition.

Leaving Guernsey, we crossed the Channel,
and landed at Weymouth the 29th of Eleventh Month;
and proceeded to visit meetings as they came in course.
John Abbott continued with me till after the Quarterly Meeting at Bridgewater;
after which he left me, and returned home, having been my companion about seven weeks.
After our parting I felt solitary--like a sparrow alone on the house-top;
but was favoured to remember that my heavenly Father careth even for the sparrows.

Proceeding onwards by Somerton, Street, Melksham,
Frome--I had meetings at these and several other places, till I came to Stockwell,
near London, to my kind friend`'s, Miller Christy,
where I arrived on the 1st of First Month, 1800.

[.embedded-content-document.letter]
--

[.letter-heading]
To His Daughter-in-law, Barbara Wigham.

[.signed-section-context-open]
Stocknell, First Month 4th, 1800.

I received thine of Twelfth Month 4th, by which I was refreshed;
it tended to renew and quicken that love and sympathy,
by which we have been and are united.
I am much in my usual way, both in body and mind,have nothing to boast of,
neither dare I complain; though I have seldom cause of rejoicing,
yet the Lord hath hitherto helped me, with a little help, for which I feel thankful.

My confidence, through mercy, still is,
that the Lord will continue to help those that trust in Him,
and who in dedication of heart give up to his requirings,
in humility and fear:--preservation in and an increase of this frame of mind,
is what I crave for myself and my dear children.

I have not been in London, though I have been here two days, within three miles of it.
I rather hope I may not be detained in the city: Sarah Lynes, Susanna Horne,
and several other friends +++[+++in the ministry,]
are engaged in it.

--

After visiting the families of Friends of Wandsworth meeting,
and attending a Quarterly Meeting at Esher in Surrey, I turned northward;
proceeding by Brentford, Staines and Uxbridge,
taking meetings in passing through Buckinghamshire, Oxfordshire, Warwickshire,
Staffordshire, Cheshire, Lancashire, part of Yorkshire, Westmoreland and Northumberland,
and so to Edinburgh; +++[+++where he arrived about the middle of the Third Month;]
and I found my dear wife and children well.
What shall I render to the Lord for all his benefits!

I stayed seven weeks at Edinburgh, except (during that time,) visiting Glasgow, Perth,
and Dundee, also settled some family matters.
Attended the Half-Year`'s Meeting,
and afterwards set out to attend the Yearly Meeting in London.
After it was over, I returned homewards by way of Wellingbro, Kettering,
Castle-Donnington, Derby, Chesterfield, Sheffield, Highflats and Wakefield:
visiting also the meetings in the Dales of Yorkshire,
and in the counties of Durham and Northumberland.
On reaching Edinburgh, I had travelled 4166 miles, and been from home upwards of a year.
After all this, I feel that I am nothing!
My heart is humbled under a sense of the Lord`'s goodness,
in enabling me to pass through so many trials and difficulties;
and I can but worship at His feet, and offer Him grateful adoration and praise.
I am yet but in the fifty-third year of my age, and have done little indeed in His cause,
compared with what He has done for me: what may be my future allotment, He only knows;
may His will be done.

The increase of bodily infirmities makes me ready to conclude,
that not much more travelling will be required; but, however this may be,
may He enable me to serve Him with a perfect heart, in the way of His own appointment;
that my few remaining days may be spent to His honour.
In many a deep exercise both at home and abroad, by sea and by land, He has been my Rock;
in long wearisome journeys on the American continent, amidst almost pathless woods,
through swamps and rivers, in the most imminent dangers,
He has preserved me;--and in my deepest baptisms He has sustained my soul.
He has won my heart by His love,
and has drawn me from my native land and near connections; He has often made a way for me,
where I could see none.
He has provided sustenance for me and my family beyond all human probability,
has made my feet like hind`'s feet,
and enabled my poor weak body to undergo almost incredible fatigue.
He hath often enabled me to set up my Ebenezer, and say,
"`Hitherto hath the Lord helped me.`"
O! what shall I render unto Him for all His benefits I write these memorandums,
that when I am gone, my children may be encouraged,
by seeing and knowing how He has supported me.

[.embedded-content-document.letter]
--

[.letter-heading]
To A. C.

[.signed-section-context-open]
Kinmuck, Sixth Month 12th, 1801.

The intelligence conveyed in thine is very grateful to me,
though some things make me sorry.
Hannah Barnard--poor creature!
I do pity, I still feel love for her;
and would fain keep hold of a hope that she will not be cast off.
The Lord is of tender mercy, though He will support His own cause;
and the foundation that He has already laid, shall never be moved,
though thousands should leave it, and build upon and lean to their own understanding.
Those who lean upon and trust in the Lord, shall never be confounded;
and I do believe that to all generations a people will be preserved, and enabled,
to hold up a testimony to the sufficiency of that foundation--the Rock,
against which He hath declared the gates of hell shall not prevail.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son-in-law, James Glenny.

[.signed-section-context-open]
Edinburgh, Third Month 15th, 1803.

Though I have frequently heard of thee since I saw thee,
yet thy mother and I are both desirous to hear from thyself how thou art;
whether the cough and expectoration are abated, and the hoarseness gone off;
and whether thou art gaining any strength.
Tell us also how thy Eliza is keeping up, and how the children are.

We feel much sympathy with you; your afflictions of one kind or another,
have not been few;
but what shall we say?--He who dispenseth such things is infinitely wise,
and knows better what is good for us than we do ourselves.
He visits with the rod in love, to promote our improvement.
Some of us need much to wean us sufficiently from things below,
and to fix our hope more steadfastly on things above, or beyond time.
May we acquiesce in the Divine will,
and endeavour to profit by the various dispensations allotted us.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son-in-law, James Glenny.

[.signed-section-context-open]
Edinburgh, Fourth Month 13th, 1803.

I received thine, and though it brought but a poor account of the state of thy health,
and increased the sympathy I feel with thee and thy Eliza; yet it was satisfactory,
inasmuch as it conveyed an evidence,
that thou receivedst this present affliction in a resigned frame of mind.
A valuable and experienced mind has said,
that the highest anthem sung in heaven is--"`Thy will be done.`"
No doubt afflicting dispensations cause a struggle in nature; but they are all in love.
The Lord corrects in mercy, and chastises those He loves; though He is just,
yet His mercy abounds; prospects in,
worldly matters are often disappointed in great mercy.
I would fondly hope the summer season may restore thee to health; but if otherwise,
the Lord`'s will must be submitted to:--the mainthing is peace,
for indeed the world is full of troubles.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To A. C.

[.signed-section-context-open]
Edinburgh, Second Month 6th, 1804.

--I have enough to do to forbear wishing to be gone;
though I know it is wrong to wish to fly whilst conflict is required;
but my faith is sometimes tried (I think) to an hair`'s-breadth,
yet in unutterable mercy it has not yet been permitted wholly to fail.
I should be an ungrateful creature, were I to utter the least complaint,
or once think suffering for Him hard, who has done so much for me.
Sometimes I am a little revived by remembering,
that the tribulated path has been the allotment of many besides me;
who have been enabled bravely to stand through their various trials, and who,
by leaning on the never-failing Helper, have been preserved through many a storm.
Dear +++_____+++, I never did nor do I aim at or expect great matters:
if I be but preserved the green shrub, it is my utmost wish.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son-in-law, James Glenny.

[.signed-section-context-open]
Edinburgh, Second Month 23rd, 1804.

By different accounts we have understood thou hast been getting worse lately.
I feel much sympathy with thee and thy dear Eliza:
no doubt it must be a trying dispensation to you both;
and unquestionably thy bodily affliction is wearisome,
and will require the exercise of patience.
The Lord only can support at such a time: may your minds be stayed upon Him,
and resignation to His will be attained.
He is all-wise, never errs, whatever He does is right.
This world at best is but a trying pilgrimage;
and when He sees meet to cut short the work,
and dissolve the tabernacle of clay at an early period,
and through his matchless mercy and forgiveness
receive the immortal part into a mansion of rest,
it is cause of humble rejoicing and adoration; and if He sees meet, as He sometimes does,
to bring down to the brink of the grave, and raise up again,
it is all in wisdom and for some good end.

It is not unusual for persons in thy situation,
when the mind is turned to look beyond time towards eternity, to have many doubtings,
and the remembrance of past failings to lie heavy upon the mind.
If this should sometimes be thy case, dear James, be not too much discouraged;
cast thyself at the feet of our dear Lord, He is merciful.
None of us have any merit of our own to plead; in His mercy is and must be all our trust.
He sets our sins in order before us, that we may be brought to an abhorrence of self,
and an adoration of His goodness; and when He has sufficiently humbled the mind,
He soothes it with the feeling of His love.^
footnote:[James Glenny, his son-in-law, died of consumption on the 1st of Eighth Month,
1804, in the 28th year of his age; leaving a widow and three children.
He appears to have made a peaceful close; having expressed to his wife,
when very near his end, that he was trusting in his Saviour,
and found nothing in the way.]

--

[.offset]
+++[+++From his Journal]

[.small-break]
'''

Edinburgh, 13th of Fourth Month, 1806.

Several years have passed over since I wrote the foregoing.
I have been, since that period, but little out of Scotland,
and nothing relative to worldly matters has particularly affected me; yet my exercises,
and days of mourning have been deep and many.
The grand adversary has obtained an entrance,
and scattered the seeds of discord among the
little flock and family of Friends of Edinburgh,
Two Months`' Meeting;
which has introduced into much trial and suffering a number among us:
and I have been at times fearful that some might fall a
prey to the devourer.--Mayst thou be pleased O Lord,
to preserve and deliver thy little trembling lambs from his paw;--
cover them with the canopy of thy love;--and be their shield,
in this and every other time of danger:--for Thou knowest,
and hast given some of us to know, that none can save us but Thee.

Fourth Month, 1807.
The Yearly Meeting`'s Committee are labouring among us:
they are evidently endowed with Divine wisdom and abundant charity,
recommending great patience and long-suffering: their labours,
and sympathy of spirit have made them near and dear to me;
and I feel an ardent desire that their labours of love may be blessed,
to the restoration of those who have been the cause of suffering,
to the relief of the sufferers,
and to the strengthening of the preciously visited children.
"`Lord, Thou alone canst, in Thy own way and time,
establish and exalt thy glorious mountain of holiness,
over everything that would exalt itself;--even so be it, Lord!
Amen.`"

The care of Edinburgh meeting having now devolved on the Yearly Meeting,
my wife and I felt easy to leave it; which we accordingly did in the Seventh Month,
and took a house at Aberdeen,
where we have been mercifully favoured to feel quiet and peaceful;
some reward for the late suffering labour at Edinburgh.

[.embedded-content-document.letter]
--

[.letter-heading]
To Ann Cruickshank.

[.signed-section-context-open]
Aberdeen, Ninth Month 4th, 1807.

I think the most I have to say is, look not too much at the dark side of things.
The things that are seen we do not hope for, but the things that are not seen.
Let us even wait long in the patience, and endeavour to fix our confidence on Him,
who knows every heart; and who will eventually take care of those,
who prefer the honour of His cause to every other thing,
who are brought to a willingness to suffer for it, if so be the Lord`'s will.
Our dear Redeemer suffered; and shall we flinch from suffering?
Do not think I am writing now as one at a distance;
for my spirit is with you in the nearest sympathy;
though I feel comforted in believing that we did right in removing,
however disadvantageous it may have been in some respects.
Our day is now pretty far spent; to look forward to the close,
through unutterable mercy is a pleasing prospect;
and yet we can by no means divest ourselves of a concern for those that may be left.
I think I may say at this time, I do prefer Jerusalem, and the welfare thereof,
to any other joy; and yet near as the end may seem to us,
new trials and conflicts may be permitted to attend our evening.
When thou canst, do pray for us, that we may hold out.

--

1808+++.+++ I felt a concern revive on my mind, to visit Friends in parts of Yorkshire,
Lincolnshire, and some places farther south.
After weighing the matter fully, I gave up to it, and informed the Monthly Meeting,
who gave me a certificate, expressing their sympathy and concurrence.

I left home, the 19th of Sixth Month, had a good passage by sea to Newcastle;
thence travelled in a gig, accompanied by my beloved friend George Richardson,
who united with me in the concern, and who had a certificate from his Monthly Meeting.
We attended York Quarterly Meeting;
then took the meetings in the North and East Ridings of Yorkshire,
crossed the Humber at Hull, and visited the meetings in Lincolnshire, Norfolk, Cambridge,
and Huntingdonshire, returned through some parts of Nottinghamshire by Sheffield,
Doncaster, Thorne, Pontefract, Ackworth, Selby, Collingworth, York; thence to Yarm,
Stockton, Sunderland, and Newcastle.
We were absent from the last place ten weeks and five days;
and according to calculation made by my companion, travelled 1171 miles,
and attended eighty-eight meetings.
I stayed some days at Newcastle, and attended their Monthly Meeting held at Shields;
where I had the pleasure of meeting with the Yearly Meeting`'s Committee,
returning from their second visit to Edinburgh.
I was pleased to observe,
that they entertained favourable hopes of improvement in that quarter,
for which I had ardently longed.

From Newcastle I went to Allendale, to see my poor aged mother;
who had been confined to bed a considerable time, in great bodily affliction,
and quite blind, but sweetly alive in spirit.
We were comforted together; but had a hard parting.
After staying a few days at Cornwood, and attending their Monthly Meeting,
I went to Sikeside meeting on First day; and on Second day, set out for Glasgow.
Andrew Phillips kindly accompanied me one stage; after which I went on alone rejoicing,
for the Lord had filled my heart with His love,
so that I could sing of mercy and of judgment.
He has, indeed, fed me in green pastures, and led me beside the still waters.
My heart was humbled under a sense of his goodness to an unworthy worm;
and my soul was filled with thanksgiving and praise.
I got to Glasgow on Fourth day, stayed over their Fifth and First day meetings,
and on Second day set off alone, and reached Aberdeen on Fifth day.
I found my family well, and did feelingly adopt the language,
"`What shall I render unto the Lord for all his benefits.`"

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Aberdeen, 8th of Tenth Month, 1808.

I got home on Fifth day, having had a long and lonely ride; but I held out pretty well,
and my mind was so peaceful, that everything seemed pleasant;
I could think nothing hard.
I found my wife and family well.--My horse held out to the end,
and I have abundance to be thankful for; indeed I seem full,
and can feelingly adopt the language, *What shall I render to the Lord,
for all his benefits?`"
May I render Him a devoted heart, for the residue of my days, is my ardent prayer.
I was much gratified by being with you;
I think it one of the many favours I am made a partaker of,
to have affectionate children; and a hope sometimes accompanies my prayers for you,
that several of you are likely to be men and women for God;
that His cause you will espouse, and even be made willing to suffer for Him,
if it be His will.
I have a testimony in my heart, that such is His goodness,
He is well worthy to be served in His own way:
may you and I be more and more dedicated to obey Him in all things.

--

I stayed about home during the winter;
my mind often much exercised upon various accounts,
particularly from a prospect that presented, of visiting Friends in and about London,
and in some of the Southern and Midland Counties.
I was much discouraged;--the declining state of my health, and my weakness in every way,
made it awful to me; but it remained and increased in weight,
till I could see no means of obtaining peace, but to yield to it.
I mentioned the subject to the Monthly Meeting in the Second Month,
desiring Friends to feel with me; and at the following meeting I requested a certificate,
which was readily granted, expressing their unity and sympathy.

[.embedded-content-document.letter]
--

[.letter-heading]
To Ann Cruickshank.

[.signed-section-context-open]
Aberdeen, 19th of First Month, 1809.

I cannot do less than acknowledge how acceptable thy letter was to me.
I sympathize with thee in my measure,
knowing how difficult it is to tread safely in the path of your allotment.
Faith and patience are doubtless necessary, but above all, a steady eye unto,
and dependence upon the Lord for help, who is the giver of both faith and patience,
and every other qualification to do His will.
We here are not without our exercises; and sensible I am, that if the Lord help us not,
we cannot stand.
Much poverty of spirit has been my allotment of late;
but I am moving on in a degree of hope.

--

On the 31st of Third Month, I accordingly set sail from Aberdeen,
had a quick and good passage of three days to London,
and was kindly received by my esteemed friends, John Sanderson and his wife.

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
London, Fourth Month 22nd, 1809.

I think it will be pleasant to thee to know that I am pretty well,
at least as well as I can expect to be in this great city,
the air of which has never agreed with me.
I have got out of it two nights in the week--have been at Stockwell, and Plaistow,
and Tottenham;--and been at meetings at the two latter places, also at Barking,
and Winchmorehill--the rest of the time has been spent in London,
where I have had meetings almost every day since I have been in it.
Every day brings a weight with it, that I cannot describe to thee;
but through adorable mercy, I hope I have been preserved from hurting the cause of Truth;
and what I have had to communicate, (I think) has met the acceptance of Friends,
and afforded relief to my own mind.
Friends have shown me much kind attention, abundantly above my desert;
for I can assure thee, I feel myself very little among the great and wise here.

--

I took meetings as they came in course, in and about London,
till the Yearly Meeting began, when I attended its sittings.
I then set out with my dear friend George Richardson,
who had previously agreed to be my companion.
We visited the meetings in Sussex and Kent; and attended the Quarterly Meeting at Dover.

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, A. W.

[.signed-section-context-open]
Dover, Sixth Month 17th, 1809.

I may tell thee that I am through mercy pretty well,
considerably better than when I left London.
We have got a mare that travels well;
and upon the whole have certainly much for which to be thankful.
We have our conflicts and trials, as I apprehend all poor travellers have,
who are exercised in our line.
We have been at all the meetings in Sussex and Kent, except Rochester,
which we intend to take in our way from Kent Quarterly Meeting to that of London;
after which, we propose taking Essex and Suffolk.

Many of the meetings in those counties we have visited,
are small meetings in every sense of the word, small as to numbers,
and in some of them little life to be felt: yet there is a remnant still preserved;
and we are abundantly satisfied,
that the Lord in mercy continues to own his seeking people,
whether collectively or separately, and is even following the revolters with the cry,
"`turn ye, turn ye, why will ye die.`"

The late Yearly Meeting was by many thought to have been a favoured time; and, perhaps,
as much harmony and condescension prevailed, as has been known for many years,
which afforded altogether, I think, an encouraging prospect;
for really the harmonizing love of our heavenly Father was frequently felt to cover us,
and many hearts I believe were filled with thankfulness.

My companion George Richardson and I travel together in much harmony,
and are often strengthened by our feelings being much in unison.
Pray for us, dear ,
that we may be preserved from hurting the cause we are seeking to promote;
and that we may not seek great things for ourselves.

--

We returned to London to the Quarterly Meeting: after which we visited meetings in Essex,
Suffolk, and the families of Friends in Norwich and in Wymondham Monthly Meetings.
We then took the meetings in Hertfordshire, Northamptonshire, and Derbyshire;
thence went to Sheffield, Wakefield, and Leeds, etc., etc.;
and by Staindrop to Newcastle.
There I left my beloved companion, and proceeded by Allendale,
Cornwood and Carlisle to Edinburgh, and so home; where I found my family in usual health:
my heart was filled with thanksgiving and praise to the God of all grace.
Though bodily infirmities frequently made travelling difficult;
and a sense of my unworthiness to be employed in so momentous a service,
made me creep along low; yet I cannot but admire the Lord`'s goodness,
and could say much in His praise; but so unworthy is my tongue to speak,
or my pen to write it, that it seems safer silently to adore.

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth (Joseph) Fry.

[.signed-section-context-open]
Aberdeen, Ninth Month 28th, 1809.

I reached home yesterday, and found my wife, children,
and other connections in usual health; which, with many more favours,
I wish I may be enough thankful for.
I cannot express what I feel,
in a sense of the Lord`'s love and condescending goodness to so unworthy a creature:
I desire to praise Him; but alas! what is my praise worth?
I desire to serve Him; but have no ability but what I receive from Him.
He is all; and I am nothing.
Amen!

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth J. Fry.

[.signed-section-context-open]
Aberdeen, Fifth Month 26th, 1810.

Under a renewed feeling of precious love, I acknowledge the receipt of thy letter:
it was very acceptable, indeed all thy communications have been pleasant to me.
Although thy mind has been much exercised on various accounts since I saw thee;
yet I am comforted in believing, that the Lord is leading about and instructing thee,
under the different dispensations that he sees meet to allot;
and even those which are the most painful ones,
are not the least profitable and instructive.
Pleasant things, such as the plentiful enjoyment of (Divine) love, light, and life,
are very grateful, and raise sensations of joy and rejoicing,
and tune our hearts to praise; but I believe the Lord is as acceptably served,
by the patient, resigned mind, in times of stripping and poverty;
which tend more to our purification,
because they often lead to deep searching of heart and humbling of spirit,
which are suitable preparations for the unfolding of the instructive counsel of the Lord,
both in what to do, and what to leave undone.

I believe, my dear friend, we cannot do better than endeavour,
through all the varied dispensations awaiting the pilgrim`'s path, to keep the eye single,
in humble dependence upon that invisible Arm of power, which often supports unseen,
and prevents our poor minds from sinking.
I feel, at this time,
almost faith enough to subscribe myself thy brother in
the tribulations and exercises of the Christian warfare:
though at times, I scarcely dare think myself one belonging to the family;
but in this degree of faith, which I now feel, I may venture to say--'`Be, of good cheer,
the Lord will not leave, nor forsake those who put their trust in Him;
who are willing to be what He would have them to be,
and to let Him work in them according to his own good pleasure.
These I believe, He will strengthen in the day of battle,
and succour in every time of need.
Therefore, my dear friend, cast all thy care upon Him,
and simply move along as He opens the way.
Thou art now, I expect, with many others engaged in the affairs of the Yearly Meeting:
my mind has been looking much towards you; and in my small measure,
I have felt concerned to pray, that Friends thus met together,
may be favoured with that one great and essential thing, power and life,
manifested through love, which begets condescension and mutual forbearance.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth J. Fry.

[.signed-section-context-open]
Aberdeen, Ninth Month 18th, 1810.

I am pleased to hear of thy satisfactory visit to+++______+++. I cannot help thinking,
that if those that incline to leave Friends, were, in sincerity,
to turn their minds to the light of Christ,
they would soon see beyond the noisy conformity to types and figures,
and be led into a more deep and sensible feeling
of the things that are spiritually discerned;
and they would be made partakers of more substantial nourishment to their souls,
than they can attain to by any external performances.
But I am afraid the cross is in the way, which they do not like to submit to.
But they must be left, hoping that when they have tried, they will, at last,
discover that it is the substance in which there is life, and not the shadow;
and this substance they must find in themselves, according to the apostle`'s testimony,
"`what is to be known of God, is manifest in man.`"

I am pleased with thy account of +++______+++,
O! may you beginners in the awful and important work of the ministry be preserved!
As thou sensibly remarks, there are many rocks, and some shoals, that are dangerous.
Sarah Robert Grubb, in one of her letters, compares us to dishes,
which must be tempered and prepared to bear the heat of the oven;
and which are more exposed to danger, than almost any other utensil at the table,
require more cleaning, and are more liable, through some indiscretion or other,
to get cracked or broken.
But though our standing may be precarious through human weakness or infirmity,
and on our part require strict watchfulness; yet there is no cause to be dismayed,
when we turn our eye to Him, who is all-powerful to preserve, full of tender compassion,
knows our frame altogether, and will preserve those who simply and humbly trust in Him.
He mercifully deals with us according to our need; clothes and strips,
feeds and proclaims fasts, reduces as well as strengthens--and all in wisdom.

There is one thing I may just mention, though perhaps I have done it before,
but it is a matter of the utmost importance;--that in our engagements in the ministry,
we simply attend to, and wait for the impulses or intimation when to speak;
and never to move without it, whatever openings or impressions we may have.
Sometimes we may have openings for our own instruction,
and sometimes we may be impressed with a sense of the state of a meeting,
or of an individual, and yet it may not be our duty to allude to it,
till we receive the intimation so to do.
If thou, my dear friend, move on in this safe way, thou wilt thrive, and grow,
and deepen in experience; and thy offerings in the ministry,
will continue to be precious and sweet, and afford the enjoyment of true peace.
Although thou mayst and will have thy plunging, trying times; yet He,
to whom thou lookest in humble dependence, will be an anchor stedfast and sure.
It is also necessary, when we do feel the clear intimation to speak,
that we be faithful to it, and not put it by,
even though it may be something disagreeable to ourselves; else we shall offend our Lord,
and weaken our own souls.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth J Fry.

[.signed-section-context-open]
Aberdeen, 6th of Fifth Month, 1811.

I have not been hasty in answering thy letter, though it was truly acceptable.
That love which waxeth not old, remains fresh with me,
with desires for thy preservation and prosperity in every good word and work.
I feel thy kindness in inviting us to the Yearly Meeting;
but our day for travelling seems nearly over.

It affords us satisfaction that we have not spared ourselves whilst ability was enjoyed;
and that now through infinite mercy,
we have no disposition to call the Lord a hard master,
but can set our seals to that great truth, that He is unspeakably good,
and has helped us far beyond our desert.
My hearty good wishes arise for those concerned brethren and sisters
who attend the Yearly Meeting:--may you be strengthened and comforted
by the fresh feeling of the uniting bond of harmonizing love:
that you may be one another`'s joy in the Lord, and enabled renewedly to praise Him; for,
verily, He hath often shewn himself good to Israel, notwithstanding all our backslidings.

--

1st of First Month, 1812.
This day begins a new year.
O Lord! from this time preserve me in exact conformity to thy will,
without spot or blemish.
I have long, thou knowest, been desirous to serve Thee with acceptance;
but I have been a poor, frail, imperfect being.
O! blot out my imperfections, gracious God! for thy dear Son`'s sake;
and enable me henceforth to serve thee better.
Destroy, O! destroy every fibre of selfishness; that what I am, I may be in Thee alone.
Amen

Second Month 1st, 1812.
I have been ruminating upon the excellency of love,
of which God is the inexhaustible fountain: it appears clear to my mind,
that in its nature and ground, it is always the same,
but flows forth differently to different objects:--to God in humble reverence and
adoration;--to good men in sweet uninterrupted unity;--to the distressed and
afflicted in sympathetic tenderness;--to the wicked and ungodly in mournful pity:
and it manifests these feelings to God by desiring and
endeavouring to do His will;--to good men by a care not to
interrupt the union;--to the distressed and afflicted by
endeavouring according to ability to relieve them;
to the wicked and ungodly by patiently bearing their insults,
and praying that they may be made better answerable to the Apostle`'s description,
bearing, hoping, and enduring all things.
There is something that some men call love, that deserves not the name;
having its foundation in a desire of the esteem of others,
which largely flows forth to such as feed this desire by flattery;
but should this be withdrawn or neglected,
and friendly reproof or admonition administered in its stead,
it manifests its spurious character by angry resentment,
and shews that it is not Christian love, but idolatry of self.

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth J. Fry.

[.signed-section-context-open]
Aberdeen, 24th of Second Month, 1812.

It would be indeed pleasant to me, as thou mentionest, to sit beside thee,
and that we might commune together in the freedom of friendship,
which I fully believe is reciprocal: but this we cannot expect to be often indulged in,
if ever any more.
But there is a comfort in feeling the circulation of
love flowing from the true source and fountain of it,
in which there is no change, and to which distance is no impediment; and,
if we are but favoured to keep our habitations in the Truth, nothing can separate us.
I feel bodily infirmities increasing, and am content that it should be so.
It is in the course of nature that this should be the case,
and the Lord`'s will is incontrovertibly best;
may nothing in me ever--even as much as wish to oppose it.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife.

[.signed-section-context-open]
Mountmellick, Twelfth Month 24th, 1812.

I received thy acceptable letter, dated 28th of last month.
It is reviving to thy poor exercised John Wigham,
to hear that thou hast faith respecting him, that the Lord will not fail him,
unworthy as he is; and as thou hast, through mercy, a little faith concerning me,
I trust it will not fail as regards thyself.

We can do no less than gratefully acknowledge,
that the Lord has been good to us hitherto; and to encourage each other to trust in Him,
is the most we can do for each other.
I am wading along in much weakness, and can only say,
I hope I have been hitherto preserved from dishonouring His cause;
and that was all I asked, at setting out.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son, Amos Wigham.

[.signed-section-context-open]
Cork, First Month 20th, 1813.

I am favoured with usual health, though I frequently feel much weariness,
and sometimes considerable pain; yet it goes off again, and upon the whole,
I have got along as well as I could expect.
The Lord has hitherto been my helper in the needful time,
and I trust preserved me from dishonouring His cause;
and also from time to time renewed a little grain of
faith and ability to place my dependence upon Him.
I cannot say much as to the time of my leaving this land;
I only desire light to discover, and ability to do His will.
He is a good master, I desire to serve Him faithfully, and that you, my dear children,
may be more and more dedicated, and a willingness wrought in you,
to be just what He would have you to be.
Mind your calling, and doubt not but He will give strength to do what He requires.
Let Him choose your stations for you, and direct your steps;
and then He will guide you in the path of safety.
The more fully and freely you give up your own wills, in conformity to the Divine will,
the less will be your conflicts under dispensations for their reduction; for I apprehend,
we often increase our sufferings,
by our unwillingness to be as the passive clay in the hand of the potter,
to be formed into such vessels as he sees meet;
and this unwillingness arises frequently from an
apprehension of our own unfitness for what He requires.
But do we not hereby show our distrust of the all-sufficiency
of His power He requires our passive obedience:
the power is His, and the qualification is His gift.

--
