== A Testimony

[.chapter-subtitle--blurb]
From Aberdeen Monthly Meeting, concerning John Wigham,
now departed this life at Aberdeen, the 17th of Fourth Month, 1839,
and was interred in Friends`' Burial-ground, at Kinmuck, the 20th of the same.
He was in the 91st year of his age, and had been a Minister about 67 years.

[quote.scripture, , Psalms 37:37]
____

"`Mark the perfect man, and behold the upright; for the end of that man is peace.`"
____

This declaration of the royal Psalmist,
we believe to be peculiarly applicable to this our dear and honoured friend;
who was enabled in the course of a long life,
faithfully to labour for the promotion of the
cause of truth and righteousness in the earth.
His end was peace.

What follows, respecting his youth and early life,
is chiefly derived from his own account left in writing.
He was born at Cornwood, in the county of Northumberland,
in the compass of Allendale Monthly Meeting.
His parents were William and Rachel Wigham,
whose religious care over him during his minority he
has recorded in terms of thankfulness and gratitude,
as having been particularly valuable to him, and especially that of his mother, who,
he says,
"`was deeply concerned that her children might be carefully educated in the way of Truth,
and preserved from the snares of the world;
she often exhorted us to be attentive to the guidance of the Holy Spirit,
secretly manifested in our own hearts, which was of great benefit to me in my childhood;
for as the Lord was graciously pleased sensibly to visit me when very young,
I was made aware,
sooner perhaps than many children who are not favoured with such instruction,
what that Spirit was, that both reproved and comforted me.

"`When I was about eight years of age,
strong desires to be the Lord`'s servant were raised in my mind;
and being made sensible that I could not serve Him acceptably,
unless I were preserved from evil, I often begged, in my childish way,
that He would enable me to overcome all my evil propensities, which I saw were many.`"
He appears to have continued much under religious exercise of mind,
and to have been preserved from many of the snares incident to youth,
until he attained to about the sixteenth year of his age; when,
having been put to work with his father`'s servants,
and not maintaining a state of watchfulness, their company proved very hurtful to him;
for beginning to take delight in folly and merriment with his companions,
he soon became leavened into their spirit; and,
though still preserved from what are deemed gross sins,
yet being led into many wrong things, his mind became alienated from his God and Saviour,
and he lost that savour of Truth, with which he had been favoured in his earlier years.
During this period of disobedience,
distress and bitterness of soul were often his portion,
and he seemed to have no power to escape from the bondage in which he was held.

At length, the Lord, in infinite compassion,
who had continued to follow him by the convictions of his Holy Spirit,
was pleased to open a way for his deliverance.
In the twenty-first year of his age,
he entered into the married state with Elizabeth Donwiddy,
who proved to him a truly faithful helpmeet.
This change of situation became the means of separating
him from the company that had led him astray;
and being mercifully favoured soon after this event,
with a fresh and powerful visitation of Divine love,
he was enabled to see the load of guilt and sin that was upon him;
under a sense whereof he was deeply humbled, and brought to sincere repentance.
The blessed fountain (he says) was set open to his view--the
blood of Christ to cleanse from all pollution,
on condition of his forsaking those things that defile;
and although he was made sensible that he had no strength of himself to forsake sin,
yet a portion of precious faith was afforded him, in the efficacy of the grace of God,
which was sufficient to give him the victory over all his spiritual enemies;
and he was preserved from fainting, and encouraged and strengthened to hold on his way,
by his gracious Redeemer manifesting Himself to be "`a High Priest touched with a
feeling of his infirmities,`"--and who was also "`his Advocate with the Father.`"
After passing through many secret exercises and conflicts of spirit,
and experiencing the operations of that baptism that cleanses the floor of the heart,
he became convinced, that, if he was faithful to what was required of him,
he must become willing to testify of the Lord`'s goodness to others;
and yielding obedience to this call, he came forth as a minister,
about the twenty-fourth year of his age.
In the exercise of his gift,
he appears to have been especially careful to keep close to the Divine openings,
waiting in all his movements for the fresh
anointing and putting forth of the good Shepherd.
Thus he became fitted for the work committed to him, and with the unity of his brethren,
was engaged, at different times, to visit in gospel love, many of the meetings,
and some of the families of Friends in several parts of England,
to the peace of his own mind.

Some time previous to the year 1783,
he was impressed with a belief that the Lord called him
to leave his native country and near connections,
and go and reside in Scotland.
This brought him under very close trial and exercise, and, for a season,
into much discouragement: he having at that time a family of seven young children,
and his means of supporting them being small,
he could not well see how they were to be provided for.
But at length he found relief in yielding up all,
in resignation to what he believed to be the Divine will;
and his faith was strengthened and confirmed in the
rectitude of the proposed movement by his beloved wife,
(who had before this time appeared as a minister,) communicating to him,
though she had no outward knowledge of his concern,
that she had in view a similar prospect.
Thus in simple faith, in obedience to the Divine requiring,
and with the concurrence of his friends, in the year 1784,
he removed with his family to the vicinity of Edinburgh.
After remaining there about two years, he came into our Monthly Meeting:
first residing at Aberdeen, and subsequently near Kinmuck.
In the year 1794, he paid a religious visit to Friends in America,
travelling among them for about three years,
both in the United States and in some of the British settlements,
holding many meetings among those not professing with us; and,
from the testimonials received,
it appears that his gospel labours were acceptable and edifying to those he visited.

After his return, in 1797, he continued a diligent labourer in his Great Master`'s cause.
In the years 1798, 1799 and 1800, he was much from home,
visiting many of the counties of England, as far as the Land`'s-end in Cornwall,
South Wales, and the island of Guernsey.
During this period, and for some years after,
he resided occasionally at his former place of abode, near Kinmuck,
but principally at Edinburgh, until the year 1807, when he left that city,
and removed to Aberdeen, which was his home during the remainder of his life.
Subsequent to this removal, he was again engaged in visiting Friends in and about London,
and many other parts of the nation; and in 1812-13,
he paid a visit to Friends in Ireland, Cumberland,
and some parts of Westmoreland and Lancashire,
which he accomplished under considerable bodily suffering:
these proved his last engagements of the kind out of Scotland.
He continued, nevertheless, while ability was afforded,
a diligent attender of meetings at home,
and visited those at a distance within the compass of his own General Meeting;
but the infirmities of age continuing to increase,
he was confined to the house for a number of years, during which, his sight,
which had been gradually becoming defective, at length totally failed,
and he was for a considerable period quite blind: this he felt a great privation,
but he was enabled to bear it, and all the other afflictions that were allotted him,
with Christian resignation and cheerfulness,
being ever more ready to number his remaining
blessings than to utter a word of complaint.

In the year 1827 he was deprived by death of his wife,
who had been his affectionate and sympathizing companion for about fifty-seven years.
Soon after this event, he penned a memorandum,
of which the following is an extract:--'`I am now in my eightieth year--a long and
weary pilgrimage;--many conflicts--many trying exercises have attended me,
yet through all the Lord has sustained me.
It seems as if I had well nigh finished my course.
I say not, I have kept the faith, but the Lord has kept me in the faith;
and I feel near and dear to me his precious cause, which, I believe,
He engaged me to advocate;
and though day after day passes over in much weariness of the flesh, yet,
by his sustaining love, the bitter is sometimes made sweet,
and what would otherwise seem hard is made easy.
I feel constrained to say, that the Lord is good--inexpressibly good;
and I have an unshaken hope, which is the precious gift of God, that,
when the conflicts of time are over, I shall enter a region of everlasting rest, peace,
and joy.
I sensibly feel I have no merit;
I am unworthy of the least of the mercies bestowed upon me: the love, grace,
and mercy of God in Christ Jesus has done all for me.
By faith my dear wife obtained the victory, and was enabled to triumph over death, hell,
and the grave; as evinced by almost her last expressions,
praising the Lord with her latest breath.
I feel the loss of her company,
but I do not regret that she is gone before me (as I trust) to be with Christ,
which is far better.`"

As a minister, he was much esteemed among us,
being sound in the Christian faith and doctrine, exemplifying by a life of self-denial,
the precepts of the gospel, being truly "`an example to the believers, in word,
in conversation, in charity, in faith, in purity.`"

During his long confinement,
our dear friend having been favoured to have his memory clear and retentive,
and his mental powers unimpaired,
he continued to take a lively interest in all that
concerned the best welfare of his fellow-professors,
and the prosperity of our religious Society.
He frequently expressed deep regret for those amongst us, who, as he believed,
were "`forsaking the fountain of living waters, and hewing them out cisterns,
broken cisterns, that can hold no water;`" but he was nevertheless confirmed in a belief,
that, though the Lord had permitted a sifting time,
He had not forsaken his people;--that eventually the
testimonies of Truth committed to our predecessors,
would be more and more conspicuously exalted among mankind.

The meetings of ministers and elders for several years were held at his house;
at the conclusion of one of these,
he expressed himself to the following effect:--"`As
this is probably the last time I shall sit with you,
in this capacity, I feel free to tell you, that all is well.
I have not been following cunningly devised fables;
neither have I been endeavouring to serve the Lord for nought,
notwithstanding my unworthiness, my many weaknesses, and shortcomings.
He has richly rewarded me--and I may also tell you,
that if you continue to persevere in faith and patience, in stability of conduct,
He will crown your latter end with lovingkindness and tender mercies,
as He is abundantly doing for me.`"

About three weeks before his final close,
his sufferings were often very distressing to him,
and he sometimes expressed a desire to be unclothed of mortality;
but in giving utterance to such a wish, he never failed to add,
"`When the right time comes.--It is the Lord`'s will that I am kept here,
and it must be right; He doeth all things well, and we are called to suffer,
as well as to do his will.`"

On one occasion, on being asked how he was, he replied,
"`I am just about as weak and poorly as I can well be,
but I have a hope--I am favoured with a lively hope, that, when I have done with time,
I shall have peace forever.`"
And, on its being remarked to him,
that it was a great mercy to have such a feeling to sustain him, he replied,
"`O yes! and none can tell how precious it is, but those who feel it.`"
At another time, in a fit of pain and sickness, thinking his end was near,
he sent for some of his family who were not then with him,
to whom he signified his readiness to depart, saying,
he had no desire to be anything but what the Lord would have him to be,
wholly resigned to His will; and, addressing himself to those around him, said, "`You,
too, must follow on,
never let go your hold,--keep to the Rock that never failed any one.`"

During the few days he continued after this, he seemed to wish for quietness,
and said but little; yet evincing at different times,
so long as the power of articulation remained,
his unshaken confidence in his God and Saviour, saying, he had nothing to trust to,
but the goodness and mercy of the Almighty.

Thus he finished his course, full of days and full of peace.
His memory is precious to us;
and we reverently believe his redeemed spirit is numbered among those,
who "`came out of great tribulation, and have washed their robes,
and made them white in the blood of the Lamb.`"

Given forth by the said Monthly Meeting held at Aberdeen, the 15th of Fourth Month, 1840,
and signed therein by a number of men and women Friends.
General Meeting for Scotland, held at Edinburgh, 4th of Fifth Month, 1840.
"`The foregoing Testimony on behalf of our late dear friend John Wigham,
has been received from Aberdeen Monthly Meeting, and being approved,
is signed on behalf of the meeting.`"

[.signed-section-signature]
William Miller, Clerk.

Signed in and on behalf of the women`'s meeting, held at the same time and place.

[.signed-section-signature]
Lucy Cruickshank, Clerk.

[.blurb]
=== The Testimony of Aberdeen Monthly Meeting concerning Elizabeth Wigham.

It having pleased the Lord to remove from a state of probation,
this our much beloved friend,
we deem it a duty incumbent on us to give forth a testimony respecting her.

She was born at Ambroseholm, near Carlisle, in the county of Cumberland, in the year 1748.
Of the early part of her life few incidents are
recollected which appear likely to afford instruction.
In 1769, she entered into the married state with our valued friend John Wigham,
then of Cornwood, within the compass of Allendale Monthly Meeting,
to whom she was a true helpmate for upwards of fifty-seven years.

A few years after her marriage, she came forth in public testimony,
having passed through much previous exercise,
and many deep baptisms under the Lord`'s preparing hand, for so important a work;
and by waiting carefully in humility for the openings of Truth, she grew in her gift,
and met with the unity of Friends in the exercise thereof.

About the year 1784, she united with her husband in a concern and belief,
that the Lord called them to leave their native country,
and to go and reside in Scotland;
which they did with the unity and concurrence of
the Monthly Meeting to which they belonged,
having then a family of seven children.
This with other movements in Scotland proved a great trial of their faith,
and subjected them to many privations and difficulties, to which she piously submitted,
trusting in Him, who she believed had called them to so great and weighty a service.
On her first removal into Scotland,
she resided in the neighbourhood of Edinburgh for about two years,
and afterwards came to live within the compass of this meeting;
and after a subsequent removal again to Edinburgh, in the year 1802,
she finally returned to us in 1807, and remained our member till her decease.

In the love of the gospel, and under an apprehension of duty,
she was at several times engaged, with the concurrence of her Monthly Meeting,
to visit the meetings of Friends in various parts of England;
and twice those in Wales and Ireland.
She also felt herself engaged several times to take up a
temporary residence within the limits of particular meetings:
these services were to her, we believe, rendered very weighty and awful;
yet she evinced her dedication, by yielding in faith and simple obedience;
thus furnishing an instructive and encouraging example to others,
who may be called to tread in a similar path.
On these occasions, as well as in her more distant travels, we have cause to believe,
that her gospel labours were to the satisfaction of those whom she visited,
and yielded the reward of peace to her own mind.

When not engaged in religious service from home,
a large family of children necessarily occupied much of her attention;
and she manifested an earnest and affectionate solicitude for their best interest,
being careful, as they advanced in years, to discourage everything in them,
which might lead from the simplicity of Truth.
Yet she did not suffer these cares (important as
they are) to prevent her from going forth,
when and where, she believed her Divine Master called her;
and on her return from these engagements she cheerfully
entered again into her domestic concerns,
in which she was a pattern of industry and frugality.

She was a diligent attender of our religious meetings; and even in her declining years,
when labouring under the pressure of much bodily infirmity and weakness,
she was a striking example of perseverance in the performance of this important duty.

Her ministry was lively and fervent, and although not adorned with much learning,
was clear, sound, and pertinent; an evidence attending,
that it proceeded from the right spring.
In the exercise of her gift,
she was often favoured to speak with great clearness to
the states of those whom she addressed,
as divers can testify, on whose minds she has left seals of her ministry.

During the forepart of her illness, she expressed but little;
indeed her day`'s work seemed to be done,
and that she only was waiting to be released from the shackles of mortality:
but it was evident to those about her, that her faith was fixed on the immutable Rock,
and her soul anchored on her God.
On one occasion, after a season of conflict,
she broke forth in the following expressions, "`O death! where is thy sting?
O grave where is thy victory?`"
and then added, "`I believe the grave will have no victory over me;
for the eternal God is my refuge, and his everlasting arm is underneath;
and that is more to me than thousands of gold and silver,
blessed and praised be his holy name.`"
At another time, she said to one of her children, "`I believe I am wearing away fast,
at least I hope so;`" and on taking leave said, "`Farewell my dear;
and mayst thou fare well in the Lord thy God;
and this is the desire of my heart for all my children.`"

As the tenor of her life appeared to breathe her Creator`'s praise;
so in her death we believe she was of the number of those,
who are said to have "`come out of great tribulation, and have washed their robes,
and made them white in the blood of the Lamb.`"
May we her survivors be animated by her example of dedication, so to follow her,
as she endeavoured to follow Christ,--that our end may be alike peaceful;
and that we may through redeeming love and mercy,
be admitted into an eternity of rest with the Lord,
where we have no doubt her purified spirit is entered.

She quietly departed this life at Aberdeen, the place of her residence,
on the 16th of the Fourth Month, 1827, and her remains were interred at Kinmuck,
on the 20th of the same.
She was in the seventy-ninth year of her age, and a minister upwards of fifty years.

Signed on behalf of our aforesaid meeting, held at Aberdeen, the 16th of Fourth Month,
1828.

[.signed-section-signature]
Jane Cruickshank.
Amos Cruickshank.
Barbara Wigham.
John Cruickshank.
Mary Gray.
Robert Gray.
Elizabeth Brantingham.
James Morris.
Hannah Wigham.
John Glenny, Clerk.
Barbara Johnston.
John Wigham.
Hannah Cruickshank, Clerk.
Amos Wigham.
Clerk.
George Brantingham, James Gray, John Robb.

The following friends, as also John Wigham,
were prevented from attending the meeting by indisposition,
but felt desirous to subscribe their names to the foregoing testimony, Alexander Robb,
William Joss, Elizabeth Glenny, Jane Robb, Margaret Robb, Sarah Cruickshank.

The foregoing Testimony having been read and
approved in the General Meeting for Scotland,
held at Edinburgh, this 28th day of Fourth Month, 1828, is signed in,
and on behalf thereof, by

[.signed-section-signature]
William Smeal, Jun., Clerk.

Signed, in and on behalf of the Women`'s Meeting.

[.signed-section-signature]
Jane Wigham, Clerk
